Repository Kernel360/f1-Orury-Backend, pull requests merged in 2023-12, with the labels that each got.

#2 [CHORE] 프로젝트 세팅
  .gitignore
  HELP.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  orury.iml
  settings.gradle
  src/main/java/org/fastcampus/orury/OruryApplication.java
  src/main/java/org/fastcampus/orury/base/db/AuditingField.java
  src/main/java/org/fastcampus/orury/batch/Test.java
  src/main/java/org/fastcampus/orury/domain/board/controller/BoardController.java
  src/main/java/org/fastcampus/orury/domain/board/converter/dto/Test.java
  src/main/java/org/fastcampus/orury/domain/board/converter/request/Test.java
  src/main/java/org/fastcampus/orury/domain/board/converter/response/Test.java
  src/main/java/org/fastcampus/orury/domain/board/db/model/Test.java
  src/main/java/org/fastcampus/orury/domain/board/db/repository/Test.java
  src/main/java/org/fastcampus/orury/domain/board/service/BoardService.java
  src/main/java/org/fastcampus/orury/domain/comment/controller/CommentController.java
  src/main/java/org/fastcampus/orury/domain/comment/converter/dto/Test.java
  src/main/java/org/fastcampus/orury/domain/comment/converter/request/Test.java
  src/main/java/org/fastcampus/orury/domain/comment/converter/response/Test.java
  src/main/java/org/fastcampus/orury/domain/comment/db/model/Test.java
  src/main/java/org/fastcampus/orury/domain/comment/db/repository/Test.java
  src/main/java/org/fastcampus/orury/domain/comment/service/CommentService.java
  src/main/java/org/fastcampus/orury/domain/notification/controller/NotificationController.java
  src/main/java/org/fastcampus/orury/domain/notification/converter/dto/Test.java
  src/main/java/org/fastcampus/orury/domain/notification/converter/request/Test.java
  src/main/java/org/fastcampus/orury/domain/notification/converter/response/Test.java
  src/main/java/org/fastcampus/orury/domain/notification/db/model/Test.java
  src/main/java/org/fastcampus/orury/domain/notification/db/repository/Test.java
  src/main/java/org/fastcampus/orury/domain/notification/service/NotificationService.java
  src/main/java/org/fastcampus/orury/domain/post/controller/PostController.java
  src/main/java/org/fastcampus/orury/domain/post/converter/dto/Test.java
  src/main/java/org/fastcampus/orury/domain/post/converter/request/Test.java
  src/main/java/org/fastcampus/orury/domain/post/converter/response/Test.java
  src/main/java/org/fastcampus/orury/domain/post/db/model/Test.java
  src/main/java/org/fastcampus/orury/domain/post/db/repository/Test.java
  src/main/java/org/fastcampus/orury/domain/post/service/PostService.java
  src/main/java/org/fastcampus/orury/domain/user/controller/UserController.java
  src/main/java/org/fastcampus/orury/domain/user/converter/dto/Test.java
  src/main/java/org/fastcampus/orury/domain/user/converter/request/Test.java
  src/main/java/org/fastcampus/orury/domain/user/converter/response/Test.java
  src/main/java/org/fastcampus/orury/domain/user/db/model/Test.java
  src/main/java/org/fastcampus/orury/domain/user/db/repository/Test.java
  src/main/java/org/fastcampus/orury/domain/user/service/UserService.java
  src/main/java/org/fastcampus/orury/global/config/Test.java
  src/main/java/org/fastcampus/orury/global/constants/Test.java
  src/main/java/org/fastcampus/orury/global/error/Test.java
  src/main/java/org/fastcampus/orury/util/Test.java
  src/main/resources/application.yaml
  src/test/java/org/fastcampus/orury/OruryApplicationTests.java
Labels: ⚙️Settings

#3 [CHORE] #1 환경 설정
  build.gradle
Labels: ⚙️Settings

#9 Refactor : #8 Auditng field 변경
  orury-api/src/main/java/org/fastcampus/oruryapi/base/db/AuditingField.java
Labels: 🔨 Refactor

#12 Feature : #10 admin domain
  build.gradle
  orury-admin/build.gradle
  orury-admin/src/main/java/org/fastcampus/oruryadmin/domain/admin/controller/AdminController.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/domain/admin/converter/dto/AdminDto.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/domain/admin/db/model/Admin.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/domain/admin/db/repository/AdminRepository.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/domain/admin/service/AdminService.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/domain/base/db/AuditingField.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/domain/notice/controller/NoticeController.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/domain/notice/converter/dto/NoticeDto.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/domain/notice/db/model/Notice.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/domain/notice/db/repository/NoticeRepository.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/domain/notice/service/NoticeService.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/domain/userwithdrawal/controller/UserWithdrawalController.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/domain/userwithdrawal/service/UserWithdrawalService.java
  orury-admin/src/main/resources/application.properties
  orury-admin/src/main/resources/application.yaml
Labels: ✨ Feature

#18 Refactor : Admin 수정
  orury-admin/src/main/java/org/fastcampus/oruryadmin/domain/admin/converter/dto/AdminDto.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/domain/admin/db/model/Admin.java
Labels: 🔨 Refactor

#22 Settings : Swagger-ui 세팅
  orury-api/src/main/java/org/fastcampus/oruryapi/global/config/SwaggerConfig.java
  orury-api/src/main/java/org/fastcampus/oruryapi/global/config/Test.java
Labels: ⚙️Settings

#24 Feat : 에러코드 & 예외처리 및 응답 메시지 껍데기 생성
  orury-api/src/main/java/org/fastcampus/oruryapi/base/converter/ApiResponse.java
  orury-api/src/main/java/org/fastcampus/oruryapi/global/error/BusinessException.java
  orury-api/src/main/java/org/fastcampus/oruryapi/global/error/GlobalExceptionHandler.java
  orury-api/src/main/java/org/fastcampus/oruryapi/global/error/code/ErrorCode.java
  orury-api/src/main/java/org/fastcampus/oruryapi/global/error/dto/ErrorResponse.java
Labels: ⚙️Settings, 💻 BE

#26 Settings : 상수 및 메시징 처리
  orury-api/src/main/java/org/fastcampus/oruryapi/global/constants/Constants.java
  orury-api/src/main/java/org/fastcampus/oruryapi/global/constants/Test.java
  orury-api/src/main/java/org/fastcampus/oruryapi/global/message/error/ErrorMessage.java
  orury-api/src/main/java/org/fastcampus/oruryapi/global/message/info/InfoMessage.java
Labels: ⚙️Settings, 💻 BE

#33 Feature : JWT 토큰 로직 구현(초안)
  build.gradle
  orury-admin/src/main/java/org/fastcampus/oruryadmin/OruryAdminApplication.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/domain/admin/controller/AdminController.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/domain/admin/converter/dto/AdminDto.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/domain/admin/converter/dto/AdminPrincipal.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/domain/admin/converter/response/AdminResponse.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/domain/admin/db/model/Admin.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/domain/admin/db/repository/AdminRepository.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/domain/admin/service/AdminService.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/domain/base/db/AuditingField.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/global/security/config/SecurityConfig.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/global/security/dto/AuthenticationAdmin.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/global/security/dto/RoleType.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/global/security/dto/login/request/LoginRequest.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/global/security/dto/login/response/LoginResponse.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/global/security/jwt/JwtAccessDeniedHandler.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/global/security/jwt/JwtAuthenticationEntryPoint.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/global/security/jwt/JwtToken.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/global/security/jwt/JwtTokenFilter.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/global/security/jwt/JwtTokenProvider.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/global/security/service/SecurityService.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/global/security/util/SecurityUtil.java
  orury-admin/src/main/resources/application.yaml
  orury-core/src/main/java/org/fastcampus/orurycore/config/FlywayConfig.java
  orury-core/src/main/resources/db/migration/V1.0.0__init.sql
Labels: ⚙️Settings, 💻 BE, 📬 API, ✨ Feature, 🔨 Refactor

#35 Chore : API 모듈의 도메인 Entity Column Name 명시
  orury-api/src/main/java/org/fastcampus/oruryapi/base/db/AuditingField.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/comment/db/model/Comment.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/comment/db/model/CommentLike.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/comment/db/model/CommentLikePK.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/db/model/Post.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/db/model/PostLike.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/db/model/PostLikePK.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/db/model/User.java
  orury-core/src/main/resources/db/migration/V1.0.0__init.sql
Labels: Chore, 💻 BE

#38 Refactor : Entity equels()/hashCode() Annotation으로 변경
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/comment/db/model/Comment.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/comment/db/model/CommentLike.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/db/model/Post.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/db/model/PostLike.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/converter/dto/UserDto.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/db/model/User.java
Labels: 💻 BE, 🔨 Refactor

#39 Settings : 멀티 모듈 최종 반영 및 Column 명세
  build.gradle
  orury-admin/build.gradle
  orury-admin/src/main/java/org/fastcampus/oruryadmin/domain/admin/db/model/Admin.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/domain/notice/db/model/Notice.java
  orury-api/build.gradle
  orury-batch/build.gradle
  orury-core/build.gradle
Labels: ⚙️Settings, 🔨 Refactor

#40 Feat : 로그인 기능 초안 작성
  build.gradle
  orury-admin/src/main/java/org/fastcampus/oruryadmin/domain/base/db/AuditingField.java
  orury-api/src/main/java/org/fastcampus/oruryapi/OruryApiApplication.java
  orury-api/src/main/java/org/fastcampus/oruryapi/base/db/AuditingField.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/auth/controller/AuthController.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/auth/converter/dto/Test.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/auth/converter/request/SignInRequest.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/auth/converter/response/Test.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/auth/db/repository/UserRepository.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/auth/service/AuthService.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/controller/UserController.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/converter/dto/UserDto.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/converter/request/Test.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/db/repository/Test.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/db/repository/UserRepository.java
  orury-api/src/main/java/org/fastcampus/oruryapi/global/config/SecurityConfig.java
  orury-api/src/main/java/org/fastcampus/oruryapi/global/constants/Constants.java
  orury-api/src/main/java/org/fastcampus/oruryapi/global/message/error/ErrorMessage.java
  orury-api/src/main/java/org/fastcampus/oruryapi/global/message/info/InfoMessage.java
  orury-api/src/main/resources/application.yaml
  orury-api/src/test/java/org/fastcampus/oruryapi/domain/auth/service/AuthServiceTest.java
  orury-core/src/main/resources/application.yaml
  orury-core/src/main/resources/db/migration/V1.0.1__drop_user_type.sql
Labels: 💻 BE, ✨ Feature

#41 Feat: User CRUD 기능
  orury-api/src/main/java/org/fastcampus/oruryapi/OruryApiApplication.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/board/converter/request/Test.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/controller/UserController.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/converter/request/IdRequest.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/converter/request/ProfileImageRequest.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/converter/request/UserInfoRequest.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/converter/response/MypageResponse.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/converter/response/Test.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/db/model/User.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/db/model/UserEnums.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/db/repository/UserRepository.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/service/UserService.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/util/UserMessage.java
  orury-api/src/main/java/org/fastcampus/oruryapi/global/error/code/UserErrorCode.java
  orury-api/src/main/java/org/fastcampus/oruryapi/global/message/error/ErrorMessage.java
  orury-core/src/main/java/org/fastcampus/orurycore/config/FlywayConfig.java
  orury-core/src/main/resources/db/migration/V1.0.0__init.sql
Labels: 💻 BE, ✨ Feature

#46 Feature/#28 post(게시글) crud
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/comment/db/repository/CommentRepository.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/controller/PostController.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/controller/PostLikeController.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/converter/dto/PostDto.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/converter/dto/PostLikePKDto.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/converter/request/PostCreateRequest.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/converter/request/PostLikeRequest.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/converter/request/PostUpdateRequest.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/converter/response/PostResponse.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/converter/response/PostsResponse.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/converter/response/PostsWithCursorResponse.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/converter/response/Test.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/db/model/Post.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/db/model/PostLike.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/db/model/PostLikePK.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/db/repository/PostLikeRepository.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/db/repository/PostRepository.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/db/repository/Test.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/service/PostLikeService.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/service/PostService.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/converter/dto/UserDto.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/db/model/User.java
  orury-api/src/main/java/org/fastcampus/oruryapi/global/config/JpaAuditingConfig.java
  orury-api/src/main/java/org/fastcampus/oruryapi/global/config/SecurityConfig.java
  orury-api/src/main/java/org/fastcampus/oruryapi/global/constants/Constants.java
  orury-api/src/main/java/org/fastcampus/oruryapi/global/error/code/PostErrorCode.java
  orury-api/src/main/java/org/fastcampus/oruryapi/global/message/info/InfoMessage.java
  orury-core/src/main/resources/db/migration/V1.0.0__init.sql
  orury-core/src/main/resources/db/migration/V1.0.1__drop_user_type.sql
Labels: Chore, 💻 BE, ✨ Feature

#48 Refactor : 컨벤션에 맞게 Post(게시글) 코드 수정
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/controller/PostController.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/controller/PostLikeController.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/converter/response/PostsWithCursorResponse.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/error/PostErrorCode.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/service/PostLikeService.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/service/PostService.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/util/PostMessage.java
  orury-api/src/main/java/org/fastcampus/oruryapi/global/constants/Constants.java
  orury-api/src/main/java/org/fastcampus/oruryapi/global/constants/NumberConstants.java
  orury-api/src/main/java/org/fastcampus/oruryapi/global/message/info/InfoMessage.java
Labels: 💻 BE, 🔨 Refactor

#56 Feat : Comment(댓글) 좋아요 기능 구현
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/comment/controller/CommentLikeController.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/comment/converter/dto/CommentLikePKDto.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/comment/converter/request/CommentLikeRequest.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/comment/db/repository/CommentLikeRepository.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/comment/service/CommentLikeService.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/converter/request/PostCreateRequest.java
  orury-core/src/main/resources/db/migration/V1.0.0__init.sql
Labels: 💻 BE, 📬 API, ✨ Feature

#58 Refactor : 게시글 CRUD 리팩토링 진행
  orury-api/src/main/java/org/fastcampus/oruryapi/base/converter/ApiResponse.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/auth/controller/AuthController.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/auth/converter/request/SignUpRequest.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/controller/PostController.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/converter/dto/PostDto.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/converter/request/PostCreateRequest.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/converter/request/PostUpdateRequest.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/converter/response/PostResponse.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/converter/response/PostsResponse.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/db/model/Post.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/db/repository/PostRepository.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/error/PostErrorCode.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/service/PostLikeService.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/service/PostService.java
  orury-api/src/main/resources/application.yaml
  orury-core/src/main/resources/application.yaml
  orury-core/src/main/resources/db/migration/V1.0.0__init.sql
Labels: 💻 BE, 📬 API, 🔨 Refactor

#60 Refactor : Post(게시글)&PostLike(게시글좋아요) Refactoring
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/controller/PostLikeController.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/converter/request/PostLikeRequest.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/db/model/PostLike.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/db/repository/PostLikeRepository.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/db/repository/PostRepository.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/service/PostLikeService.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/service/PostService.java
Labels: 💻 BE, 🔨 Refactor

#63 Feat : 인기게시글 조회 API 구현
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/controller/PostController.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/converter/response/PostsResponse.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/converter/response/PostsWithCursorResponse.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/converter/response/PostsWithPageResponse.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/db/repository/PostRepository.java
  orury-api/src/main/java/org/fastcampus/oruryapi/domain/post/service/PostService.java
  orury-api/src/main/java/org/fastcampus/oruryapi/global/constants/NumberConstants.java
Labels: 💻 BE, ✨ Feature

#68 Chore : 패키지 구조를 잘 확인하자!!
  orury-client/build.gradle
  orury-domain/src/main/resources/db/migration/V1.0.0__init.sql
Labels: Chore

#71 Test : 게시글 CRUD 관련 Service Layer 테스트코드 추가
  orury-client/src/test/java/org/fastcampus/oruryclient/post/service/PostServiceTest.java
Labels: 💻 BE, ✅ Test

#72 Refactor : comment(댓글) refactoring
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/controller/CommentController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/controller/CommentLikeController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/converter/request/CommentCreateRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/converter/request/CommentUpdateRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/converter/response/ChildCommentResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/converter/response/CommentResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/converter/response/CommentsWithCursorResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/error/CommentErrorCode.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/service/CommentLikeService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/service/CommentService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/controller/PostController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/controller/PostLikeController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/converter/request/PostLikeRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/service/PostLikeService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/service/PostService.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/comment/db/model/Comment.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/comment/db/repository/CommentLikeRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/comment/db/repository/CommentRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/comment/dto/CommentDto.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/comment/dto/CommentLikePKDto.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/post/db/repository/PostLikeRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/post/db/repository/PostRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/post/dto/PostLikePKDto.java
  orury-domain/src/main/resources/db/migration/V1.0.1__add_viewCount_column_to_comment_table.sql
Labels: 💻 BE, 🔨 Refactor

#75 Refactor : API 응답 isMine 추가에 따른 리팩토링
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/controller/CommentController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/converter/response/CommentResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/service/CommentLikeService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/service/CommentService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/controller/PostController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/converter/request/PostCreateRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/converter/request/PostUpdateRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/converter/response/PostResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/service/PostLikeService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/service/PostService.java
Labels: 💻 BE, 🔨 Refactor

#73 게시글 좋아요 테스트 코드
  orury-client/src/test/java/org/fastcampus/oruryclient/OruryClientApplicationTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/post/service/PostLikeServiceTest.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/post/dto/PostLikeDto.java
Labels: ✅ Test

#78 Settings/#43 GitHub actions
  .github/workflows/gradle.yml
  build.gradle
  orury-admin/settings.gradle
  orury-admin/src/test/java/org/fastcampus/oruryadmin/OruryAdminApplicationTests.java
  orury-client/build.gradle
  orury-client/settings.gradle
  orury-client/src/main/resources/application.yaml
  orury-client/src/test/java/org/fastcampus/oruryclient/domain/user/db/repository/UserRepositoryTest.java
  orury-common/build.gradle
Labels: ⚙️Settings
