Repository Kernel360/f1-Orury-Backend, pull requests merged in 2024-05, with the labels that each got.

#452 Refactor : 회원가입 시, 프로필이미지 업로드 가능하도록 수정
  orury-client/src/main/java/org/orury/client/auth/application/AuthFacade.java
  orury-client/src/main/java/org/orury/client/auth/application/AuthService.java
  orury-client/src/main/java/org/orury/client/auth/application/AuthServiceImpl.java
  orury-client/src/main/java/org/orury/client/auth/interfaces/AuthController.java
  orury-client/src/main/java/org/orury/client/auth/interfaces/request/SignUpRequest.java
  orury-client/src/test/java/org/orury/client/auth/application/AuthFacadeTest.java
  orury-client/src/test/java/org/orury/client/auth/application/AuthServiceImplTest.java
  orury-client/src/test/java/org/orury/client/config/ServiceTest.java
Labels: 💻 BE, 🔨 Refactor

#453 Feat : 신고기능 개발
  orury-client/src/main/java/org/orury/client/user/application/UserFacade.java
  orury-client/src/main/java/org/orury/client/user/application/UserService.java
  orury-client/src/main/java/org/orury/client/user/application/UserServiceImpl.java
  orury-client/src/main/java/org/orury/client/user/interfaces/UserController.java
  orury-client/src/main/java/org/orury/client/user/interfaces/message/UserMessage.java
  orury-client/src/main/java/org/orury/client/user/interfaces/request/UserReportRequest.java
  orury-client/src/test/java/org/orury/client/ClientFixtureFactory.java
  orury-client/src/test/java/org/orury/client/config/ServiceTest.java
  orury-client/src/test/java/org/orury/client/user/application/UserFacadeTest.java
  orury-client/src/test/java/org/orury/client/user/application/UserServiceImplTest.java
  orury-common/src/main/java/org/orury/common/error/code/UserErrorCode.java
  orury-domain/src/main/java/org/orury/domain/user/domain/ReportReader.java
  orury-domain/src/main/java/org/orury/domain/user/domain/ReportStore.java
  orury-domain/src/main/java/org/orury/domain/user/domain/dto/ReportDto.java
  orury-domain/src/main/java/org/orury/domain/user/domain/dto/ReportInfo.java
  orury-domain/src/main/java/org/orury/domain/user/domain/dto/ReportType.java
  orury-domain/src/main/java/org/orury/domain/user/domain/entity/Report.java
  orury-domain/src/main/java/org/orury/domain/user/infrastucture/ReportReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/user/infrastucture/ReportRepository.java
  orury-domain/src/main/java/org/orury/domain/user/infrastucture/ReportStoreImpl.java
  orury-domain/src/main/resources/db/migration/V1.0.38__create_report_table.sql
  orury-domain/src/test/java/org/orury/domain/config/InfrastructureTest.java
  orury-domain/src/test/java/org/orury/domain/user/infrastructure/ReportStoreImplTest.java
  orury-domain/src/testFixtures/java/org/orury/domain/UserDomainFixture.java
Labels: 💻 BE, 📬 API, ✨ Feature

#455 Db : 유저 테이블에 자기소개(self_introduction) 필드 추가
  orury-client/src/main/java/org/orury/client/auth/interfaces/request/SignUpRequest.java
  orury-client/src/main/java/org/orury/client/user/application/UserFacade.java
  orury-client/src/main/java/org/orury/client/user/interfaces/UserController.java
  orury-client/src/main/java/org/orury/client/user/interfaces/request/UserInfoRequest.java
  orury-client/src/main/java/org/orury/client/user/interfaces/response/MypageResponse.java
  orury-domain/src/main/java/org/orury/domain/auth/domain/dto/LoginDto.java
  orury-domain/src/main/java/org/orury/domain/user/domain/dto/UserDto.java
  orury-domain/src/main/java/org/orury/domain/user/domain/entity/User.java
  orury-domain/src/main/resources/db/migration/V1.0.39__add_self_introduction_to_user.sql
  orury-domain/src/test/java/org/orury/domain/comment/infrastructure/CommentStoreImplTest.java
  orury-domain/src/testFixtures/java/org/orury/domain/UserDomainFixture.java
Labels: 🛢 DB, 💻 BE

#447 게시글 검색 최신순, 인기순
  orury-client/src/main/java/org/orury/client/post/application/PostFacade.java
  orury-client/src/main/java/org/orury/client/post/application/PostService.java
  orury-client/src/main/java/org/orury/client/post/application/PostServiceImpl.java
  orury-client/src/main/java/org/orury/client/post/interfaces/PostController.java
  orury-client/src/test/java/org/orury/client/post/application/PostFacadeTest.java
  orury-client/src/test/java/org/orury/client/post/application/PostServiceImplTest.java
  orury-domain/src/main/java/org/orury/domain/post/domain/PostReader.java
  orury-domain/src/main/java/org/orury/domain/post/infrastructure/PostReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/post/infrastructure/PostRepository.java
  orury-domain/src/test/java/org/orury/domain/post/infrastructure/PostReaderTest.java
Labels: 💻 BE, 🔨 Refactor

#457 Feat : 센터정보에 필요한 remark값 추가
  orury-client/src/main/java/org/orury/client/gym/interfaces/response/GymResponse.java
Labels: 💻 BE, ✨ Feature

#459 Feat : 내가 저장한(좋아요 누른) 암장 목록 반환
  orury-client/src/main/java/org/orury/client/gym/application/GymService.java
  orury-client/src/main/java/org/orury/client/gym/application/GymServiceImpl.java
  orury-client/src/main/java/org/orury/client/user/application/UserFacade.java
  orury-client/src/main/java/org/orury/client/user/interfaces/UserController.java
  orury-client/src/main/java/org/orury/client/user/interfaces/message/UserMessage.java
  orury-client/src/main/java/org/orury/client/user/interfaces/response/MyGymResponse.java
  orury-client/src/test/java/org/orury/client/config/FacadeTest.java
  orury-client/src/test/java/org/orury/client/gym/application/GymServiceImplTest.java
  orury-client/src/test/java/org/orury/client/user/application/UserFacadeTest.java
  orury-domain/src/main/java/org/orury/domain/global/domain/Region.java
  orury-domain/src/main/java/org/orury/domain/gym/domain/GymReader.java
  orury-domain/src/main/java/org/orury/domain/gym/infrastructure/GymLikeRepository.java
  orury-domain/src/main/java/org/orury/domain/gym/infrastructure/GymReaderImpl.java
  orury-domain/src/test/java/org/orury/domain/gym/infrastructure/GymReaderImplTest.java
Labels: 💻 BE, ✨ Feature
