Repository Kernel360/f1-Orury-Backend, pull requests merged in 2024-03, with the labels that each got.

#320 Test : User 테스트 코드 작성
  orury-client/src/main/java/org/orury/client/comment/application/CommentFacade.java
  orury-client/src/main/java/org/orury/client/post/application/PostFacade.java
  orury-client/src/main/java/org/orury/client/review/application/ReviewFacade.java
  orury-client/src/main/java/org/orury/client/user/application/UserFacade.java
  orury-client/src/main/java/org/orury/client/user/application/UserService.java
  orury-client/src/main/java/org/orury/client/user/application/UserServiceImpl.java
  orury-client/src/main/java/org/orury/client/user/interfaces/UserController.java
  orury-client/src/test/java/org/orury/client/config/ControllerTest.java
  orury-client/src/test/java/org/orury/client/user/application/UserFacadeTest.java
  orury-client/src/test/java/org/orury/client/user/application/UserServiceImplTest.java
  orury-client/src/test/java/org/orury/client/user/db/model/UserTest.java
  orury-client/src/test/java/org/orury/client/user/service/UserServiceImplTest.java
  orury-domain/src/main/java/org/orury/domain/user/domain/UserReader.java
  orury-domain/src/main/java/org/orury/domain/user/infrastucture/UserReaderImpl.java
  orury-domain/src/test/java/org/orury/domain/user/infrastructure/UserReaderImplTest.java
  orury-domain/src/test/java/org/orury/domain/user/infrastructure/UserStoreImplTest.java
Labels: 💻 BE, ✅ Test, 🔨 Refactor

#324 Test : Comment 테스트코드 작성
  orury-client/src/test/java/org/orury/client/comment/application/CommentFacadeTest.java
  orury-client/src/test/java/org/orury/client/comment/application/CommentServiceImplTest.java
  orury-client/src/test/java/org/orury/client/comment/controller/CommentControllerTest.java
  orury-client/src/test/java/org/orury/client/comment/controller/CommentLikeControllerTest.java
  orury-client/src/test/java/org/orury/client/comment/service/CommentLikeServiceTest.java
  orury-client/src/test/java/org/orury/client/comment/service/CommentServiceTest.java
  orury-client/src/test/java/org/orury/client/gym/application/GymFacadeTest.java
  orury-client/src/test/java/org/orury/client/gym/application/GymServiceImplTest.java
  orury-client/src/test/java/org/orury/client/gym/service/GymServiceTest.java
  orury-domain/src/test/java/org/orury/domain/comment/infrastructure/CommentReaderImplTest.java
  orury-domain/src/test/java/org/orury/domain/comment/infrastructure/CommentStoreImplTest.java
  orury-domain/src/test/java/org/orury/domain/gym/infrastructure/GymReaderImplTest.java
  orury-domain/src/test/java/org/orury/domain/gym/infrastructure/GymStoreImplTest.java
Labels: 💻 BE, ✅ Test

#314 Test : 게시글 Service 테스트 작성 및 약간의 리팩터링
  orury-client/src/main/java/org/orury/client/comment/application/CommentFacade.java
  orury-client/src/main/java/org/orury/client/comment/controller/CommentController.java
  orury-client/src/main/java/org/orury/client/post/application/PostFacade.java
  orury-client/src/main/java/org/orury/client/post/application/PostService.java
  orury-client/src/main/java/org/orury/client/post/application/PostServiceImpl.java
  orury-client/src/main/java/org/orury/client/user/application/UserFacade.java
  orury-client/src/test/java/org/orury/client/comment/application/CommentFacadeTest.java
  orury-client/src/test/java/org/orury/client/config/ControllerTest.java
  orury-client/src/test/java/org/orury/client/post/service/PostLikeServiceTest.java
  orury-client/src/test/java/org/orury/client/post/service/PostServiceTest.java
  orury-client/src/test/java/org/orury/client/user/application/UserFacadeTest.java
  orury-domain/src/main/java/org/orury/domain/post/domain/PostReader.java
  orury-domain/src/main/java/org/orury/domain/post/domain/dto/PostDto.java
  orury-domain/src/main/java/org/orury/domain/post/infrastructure/ImageStoreImpl.java
  orury-domain/src/main/java/org/orury/domain/post/infrastructure/PostReaderImpl.java
  orury-domain/src/test/java/org/orury/domain/post/db/repository/PostRepositoryTest.java
Labels: 💻 BE, ✅ Test, 🔨 Refactor

#338 Fix : 리뷰 삭제 권한없음 에러 수정
  orury-client/src/main/java/org/orury/client/review/application/ReviewServiceImpl.java
Labels: 🐞 Fix, 💻 BE

#326 Feat : 좌표영역 내 암장목록 조회 api 구현
  orury-batch/src/main/java/org/orury/batch/dto/GymResponse.java
  orury-batch/src/test/java/org/orury/batch/job/StepItemTest.java
  orury-client/src/main/java/org/orury/client/gym/application/GymFacade.java
  orury-client/src/main/java/org/orury/client/gym/application/GymService.java
  orury-client/src/main/java/org/orury/client/gym/application/GymServiceImpl.java
  orury-client/src/main/java/org/orury/client/gym/interfaces/GymController.java
  orury-client/src/main/java/org/orury/client/gym/interfaces/request/AreaGrid.java
  orury-client/src/main/java/org/orury/client/gym/interfaces/request/GymAreaRequest.java
  orury-client/src/test/java/org/orury/client/gym/application/GymFacadeTest.java
  orury-client/src/test/java/org/orury/client/gym/application/GymServiceImplTest.java
  orury-client/src/test/java/org/orury/client/user/application/UserFacadeTest.java
  orury-domain/src/main/java/org/orury/domain/gym/domain/GymReader.java
  orury-domain/src/main/java/org/orury/domain/gym/domain/dto/GymDto.java
  orury-domain/src/main/java/org/orury/domain/gym/domain/entity/Gym.java
  orury-domain/src/main/java/org/orury/domain/gym/infrastructure/GymReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/gym/infrastructure/GymRepository.java
  orury-domain/src/main/java/org/orury/domain/review/infrastructures/ReviewReactionRepository.java
  orury-domain/src/main/java/org/orury/domain/review/infrastructures/ReviewReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/review/infrastructures/ReviewRepository.java
  orury-domain/src/main/java/org/orury/domain/review/infrastructures/ReviewStoreImpl.java
  orury-domain/src/test/java/org/orury/domain/config/TestRepositoryUtils.java
  orury-domain/src/test/java/org/orury/domain/gym/infrastructure/GymReaderImplTest.java
Labels: 💻 BE, ✨ Feature

#334 Feat : Crew(크루) 관련 Entity,Repository,Dto 구현 및 DB Table 추가
  orury-domain/src/main/java/org/orury/domain/crew/domain/CrewApplicationReader.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/CrewApplicationStore.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/CrewMemberReader.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/CrewMemberStore.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/CrewReader.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/CrewStore.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/dto/CrewApplicationDto.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/dto/CrewDto.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/dto/CrewMemberDto.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/entity/Crew.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/entity/CrewApplication.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/entity/CrewApplicationPK.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/entity/CrewMember.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/entity/CrewMemberPK.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewApplicationReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewApplicationRepository.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewApplicationStoreImpl.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewMemberReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewMemberRepository.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewMemberStoreImpl.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewRepository.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewStoreImpl.java
  orury-domain/src/main/java/org/orury/domain/meeting/domain/MeetingMemberReader.java
  orury-domain/src/main/java/org/orury/domain/meeting/domain/MeetingMemberStore.java
  orury-domain/src/main/java/org/orury/domain/meeting/domain/MeetingReader.java
  orury-domain/src/main/java/org/orury/domain/meeting/domain/MeetingStore.java
  orury-domain/src/main/java/org/orury/domain/meeting/domain/dto/MeetingDto.java
  orury-domain/src/main/java/org/orury/domain/meeting/domain/dto/MeetingMemberDto.java
  orury-domain/src/main/java/org/orury/domain/meeting/domain/entity/Meeting.java
  orury-domain/src/main/java/org/orury/domain/meeting/domain/entity/MeetingMember.java
  orury-domain/src/main/java/org/orury/domain/meeting/domain/entity/MeetingMemberPK.java
  orury-domain/src/main/java/org/orury/domain/meeting/infrastructure/MeetingMemberReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/meeting/infrastructure/MeetingMemberRepository.java
  orury-domain/src/main/java/org/orury/domain/meeting/infrastructure/MeetingMemberStoreImpl.java
  orury-domain/src/main/java/org/orury/domain/meeting/infrastructure/MeetingReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/meeting/infrastructure/MeetingRepository.java
  orury-domain/src/main/java/org/orury/domain/meeting/infrastructure/MeetingStoreImpl.java
  orury-domain/src/main/resources/db/migration/V1.0.21__add_crew_domain_tables.sql
Labels: 🛢 DB, 💻 BE, ✨ Feature

#346 Fix : 회원가입 후, 유효한 userId 조회
  orury-client/src/main/java/org/orury/client/auth/application/AuthServiceImpl.java
  orury-client/src/test/java/org/orury/client/auth/application/AuthServiceImplTest.java
Labels: 🐞 Fix, 💻 BE

#335 Test : 리뷰 테스트코드 작성
  orury-client/src/main/java/org/orury/client/review/application/ReviewServiceImpl.java
  orury-client/src/test/java/org/orury/client/review/application/ReviewFacadeTest.java
  orury-client/src/test/java/org/orury/client/review/application/ReviewServiceImplTest.java
  orury-domain/src/main/java/org/orury/domain/global/image/ImageStore.java
  orury-domain/src/main/java/org/orury/domain/post/infrastructure/ImageStoreImpl.java
  orury-domain/src/main/java/org/orury/domain/review/domain/ReviewReader.java
  orury-domain/src/main/java/org/orury/domain/review/infrastructure/ReviewReactionRepository.java
  orury-domain/src/main/java/org/orury/domain/review/infrastructure/ReviewReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/review/infrastructure/ReviewRepository.java
  orury-domain/src/main/java/org/orury/domain/review/infrastructure/ReviewStoreImpl.java
  orury-domain/src/test/java/org/orury/domain/review/infrastructure/ReviewReaderImplTest.java
  orury-domain/src/test/java/org/orury/domain/review/infrastructure/ReviewStoreImplTest.java
Labels: 💻 BE, ✅ Test

#343 Refactor : 유저 도메인 변경 및 Ban 유저 관련 수정사항 반영
  orury-admin/src/main/java/org/orury/admin/admin/application/AdminFacade.java
  orury-admin/src/main/java/org/orury/admin/admin/interfaces/AdminController.java
  orury-admin/src/main/java/org/orury/admin/user/UserService.java
  orury-admin/src/main/java/org/orury/admin/user/UserServiceImpl.java
  orury-client/src/main/java/org/orury/client/auth/application/AuthServiceImpl.java
  orury-client/src/main/java/org/orury/client/auth/application/jwt/JwtTokenServiceImpl.java
  orury-client/src/main/java/org/orury/client/auth/interfaces/request/SignUpRequest.java
  orury-client/src/main/java/org/orury/client/global/config/SecurityConfig.java
  orury-client/src/main/java/org/orury/client/user/interfaces/request/UserInfoRequest.java
  orury-client/src/test/java/org/orury/client/auth/application/AuthFacadeTest.java
  orury-client/src/test/java/org/orury/client/auth/application/AuthServiceImplTest.java
  orury-client/src/test/java/org/orury/client/auth/application/JwtTokenServiceImplTest.java
  orury-client/src/test/java/org/orury/client/comment/application/CommentFacadeTest.java
  orury-client/src/test/java/org/orury/client/comment/application/CommentServiceImplTest.java
  orury-client/src/test/java/org/orury/client/config/WithUserPrincipalSecurityContextFactory.java
  orury-client/src/test/java/org/orury/client/gym/application/GymFacadeTest.java
  orury-client/src/test/java/org/orury/client/post/controller/PostControllerTest.java
  orury-client/src/test/java/org/orury/client/post/service/PostServiceTest.java
  orury-client/src/test/java/org/orury/client/review/application/ReviewFacadeTest.java
  orury-client/src/test/java/org/orury/client/review/application/ReviewServiceImplTest.java
  orury-client/src/test/java/org/orury/client/review/controller/ReviewControllerTest.java
  orury-client/src/test/java/org/orury/client/review/service/ReviewReactionServiceTest.java
  orury-client/src/test/java/org/orury/client/review/service/ReviewServiceTest.java
  orury-client/src/test/java/org/orury/client/user/application/UserFacadeTest.java
  orury-client/src/test/java/org/orury/client/user/application/UserServiceImplTest.java
  orury-client/src/test/java/org/orury/client/user/controller/UserControllerTest.java
  orury-client/src/test/java/org/orury/client/user/service/UserServiceTest.java
  orury-common/src/main/java/org/orury/common/error/code/AuthErrorCode.java
  orury-domain/src/main/java/org/orury/domain/auth/domain/RefreshTokenStore.java
  orury-domain/src/main/java/org/orury/domain/auth/domain/dto/LoginDto.java
  orury-domain/src/main/java/org/orury/domain/auth/infrastructure/RefreshTokenRepository.java
  orury-domain/src/main/java/org/orury/domain/auth/infrastructure/RefreshTokenStoreImpl.java
  orury-domain/src/main/java/org/orury/domain/global/constants/Constants.java
  orury-domain/src/main/java/org/orury/domain/post/infrastructure/ImageReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/post/infrastructure/ImageStoreImpl.java
  orury-domain/src/main/java/org/orury/domain/user/domain/dto/UserDto.java
  orury-domain/src/main/java/org/orury/domain/user/domain/dto/UserStatus.java
  orury-domain/src/main/java/org/orury/domain/user/domain/dto/UserStatusConverter.java
  orury-domain/src/main/java/org/orury/domain/user/domain/entity/User.java
  orury-domain/src/main/resources/db/migration/V1.0.22__modify_user_is_deleted.sql
  orury-domain/src/test/java/org/orury/domain/comment/infrastructure/CommentReaderImplTest.java
  orury-domain/src/test/java/org/orury/domain/comment/infrastructure/CommentStoreImplTest.java
  orury-domain/src/test/java/org/orury/domain/config/TestRepositoryUtils.java
  orury-domain/src/test/java/org/orury/domain/review/infrastructure/ReviewReaderImplTest.java
  orury-domain/src/test/java/org/orury/domain/review/infrastructure/ReviewStoreImplTest.java
  orury-domain/src/test/java/org/orury/domain/user/infrastructure/UserReaderImplTest.java
  orury-domain/src/test/java/org/orury/domain/user/infrastructure/UserStoreImplTest.java
Labels: 💻 BE, 🔨 Refactor

#352 Fix : 기본 프사 삭제 현상 수정
  orury-domain/src/main/java/org/orury/domain/post/infrastructure/ImageStoreImpl.java
Labels: 🐞 Fix, 💻 BE, 📬 API

#350 Refactor : MyReviews 조회 API 응답형식 변경
  orury-client/src/main/java/org/orury/client/review/interfaces/response/ReviewsResponse.java
  orury-client/src/main/java/org/orury/client/user/application/UserFacade.java
  orury-client/src/main/java/org/orury/client/user/interfaces/response/MyReviewResponse.java
  orury-client/src/test/java/org/orury/client/user/application/UserFacadeTest.java
Labels: 💻 BE, 🔨 Refactor

#348 Refactor : user.email not null 처리
  orury-domain/src/main/resources/db/migration/V1.0.24__modify_user_email_not_null.sql
Labels: 🛢 DB, 💻 BE, 🔨 Refactor

#353 Feat : Crew 조회 API 구현
  orury-client/src/main/java/org/orury/client/crew/application/CrewFacade.java
  orury-client/src/main/java/org/orury/client/crew/application/CrewService.java
  orury-client/src/main/java/org/orury/client/crew/application/CrewServiceImpl.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/CrewController.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/message/CrewMessage.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/response/CrewResponse.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/response/CrewsResponseByMyCrew.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/response/CrewsResponseByRank.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/response/CrewsResponseByRecommend.java
  orury-common/src/main/java/org/orury/common/error/code/CrewErrorCode.java
  orury-common/src/main/java/org/orury/common/util/S3Folder.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/CrewReader.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewMemberRepository.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewRepository.java
  orury-domain/src/main/java/org/orury/domain/global/constants/NumberConstants.java
Labels: 💻 BE, ✨ Feature

#356 Fix : 리뷰 수정/삭제 권한없음 에러 재해결
  orury-client/src/main/java/org/orury/client/review/application/ReviewServiceImpl.java
  orury-client/src/test/java/org/orury/client/review/application/ReviewServiceImplTest.java
Labels: 🐞 Fix, 💻 BE, ✅ Test

#342 Feat : Meeting(크루 모임) API 구현
  orury-client/src/main/java/org/orury/client/crew/application/CrewFacade.java
  orury-client/src/main/java/org/orury/client/crew/application/CrewService.java
  orury-client/src/main/java/org/orury/client/crew/application/CrewServiceImpl.java
  orury-client/src/main/java/org/orury/client/meeting/application/MeetingFacade.java
  orury-client/src/main/java/org/orury/client/meeting/application/MeetingService.java
  orury-client/src/main/java/org/orury/client/meeting/application/MeetingServiceImpl.java
  orury-client/src/main/java/org/orury/client/meeting/interfaces/MeetingController.java
  orury-client/src/main/java/org/orury/client/meeting/interfaces/message/MeetingMessage.java
  orury-client/src/main/java/org/orury/client/meeting/interfaces/request/MeetingCreateRequest.java
  orury-client/src/main/java/org/orury/client/meeting/interfaces/request/MeetingUpdateRequest.java
  orury-client/src/main/java/org/orury/client/meeting/interfaces/response/MeetingMembersResponse.java
  orury-client/src/main/java/org/orury/client/meeting/interfaces/response/MeetingsResponse.java
  orury-client/src/test/java/org/orury/client/auth/application/AuthServiceImplTest.java
  orury-common/src/main/java/org/orury/common/config/SwaggerConfig.java
  orury-common/src/main/java/org/orury/common/error/code/CrewErrorCode.java
  orury-common/src/main/java/org/orury/common/error/code/MeetingErrorCode.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/CrewMemberReader.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/CrewReader.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewMemberReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewMemberRepository.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/global/constants/NumberConstants.java
  orury-domain/src/main/java/org/orury/domain/meeting/domain/MeetingMemberReader.java
  orury-domain/src/main/java/org/orury/domain/meeting/domain/MeetingMemberStore.java
  orury-domain/src/main/java/org/orury/domain/meeting/domain/MeetingReader.java
  orury-domain/src/main/java/org/orury/domain/meeting/domain/MeetingStore.java
  orury-domain/src/main/java/org/orury/domain/meeting/domain/dto/MeetingDto.java
  orury-domain/src/main/java/org/orury/domain/meeting/domain/entity/Meeting.java
  orury-domain/src/main/java/org/orury/domain/meeting/infrastructure/MeetingMemberReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/meeting/infrastructure/MeetingMemberRepository.java
  orury-domain/src/main/java/org/orury/domain/meeting/infrastructure/MeetingMemberStoreImpl.java
  orury-domain/src/main/java/org/orury/domain/meeting/infrastructure/MeetingReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/meeting/infrastructure/MeetingRepository.java
  orury-domain/src/main/java/org/orury/domain/meeting/infrastructure/MeetingStoreImpl.java
  orury-domain/src/main/java/org/orury/domain/user/domain/UserReader.java
  orury-domain/src/main/java/org/orury/domain/user/infrastucture/UserReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/user/infrastucture/UserRepository.java
  orury-domain/src/main/resources/db/migration/V1.0.23__add_auto_increment_to_Crew&CrewMeeting.sql
  orury-domain/src/main/resources/db/migration/V1.0.25__drop_endtime_field_in_crewmeeting_table.sql
Labels: 💻 BE, ✨ Feature

#357 Refactor : 이미지 처리 로직 Converter 사용
  orury-admin/src/main/java/org/orury/admin/post/application/PostServiceImpl.java
  orury-admin/src/main/java/org/orury/admin/user/UserServiceImpl.java
  orury-client/src/main/java/org/orury/client/comment/application/CommentServiceImpl.java
  orury-client/src/main/java/org/orury/client/gym/application/GymServiceImpl.java
  orury-client/src/main/java/org/orury/client/post/application/PostServiceImpl.java
  orury-client/src/main/java/org/orury/client/review/application/ReviewServiceImpl.java
  orury-client/src/main/java/org/orury/client/user/application/UserServiceImpl.java
  orury-client/src/main/resources/application.yml
  orury-client/src/test/java/org/orury/client/comment/application/CommentServiceImplTest.java
  orury-client/src/test/java/org/orury/client/gym/application/GymServiceImplTest.java
  orury-client/src/test/java/org/orury/client/post/service/PostServiceTest.java
  orury-client/src/test/java/org/orury/client/review/application/ReviewServiceImplTest.java
  orury-client/src/test/java/org/orury/client/user/application/UserServiceImplTest.java
  orury-common/src/main/java/org/orury/common/config/BeanUtils.java
  orury-common/src/main/java/org/orury/common/util/ImageUtil.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/entity/Crew.java
  orury-domain/src/main/java/org/orury/domain/global/image/ImageReader.java
  orury-domain/src/main/java/org/orury/domain/global/image/ImageStore.java
  orury-domain/src/main/java/org/orury/domain/global/listener/CrewImageConverter.java
  orury-domain/src/main/java/org/orury/domain/global/listener/EntityImageConverter.java
  orury-domain/src/main/java/org/orury/domain/global/listener/EntityImagesConverter.java
  orury-domain/src/main/java/org/orury/domain/global/listener/GymImagesConverter.java
  orury-domain/src/main/java/org/orury/domain/global/listener/PostImagesConverter.java
  orury-domain/src/main/java/org/orury/domain/global/listener/ReviewImagesConverter.java
  orury-domain/src/main/java/org/orury/domain/global/listener/UserProfileConverter.java
  orury-domain/src/main/java/org/orury/domain/gym/domain/entity/Gym.java
  orury-domain/src/main/java/org/orury/domain/post/domain/dto/PostDto.java
  orury-domain/src/main/java/org/orury/domain/post/domain/entity/Post.java
  orury-domain/src/main/java/org/orury/domain/post/infrastructure/ImageReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/post/infrastructure/ImageStoreImpl.java
  orury-domain/src/main/java/org/orury/domain/review/domain/entity/Review.java
  orury-domain/src/main/java/org/orury/domain/user/domain/dto/UserDto.java
  orury-domain/src/main/java/org/orury/domain/user/domain/entity/User.java
Labels: 💻 BE, 🔨 Refactor

#360 develop merge into stage
  orury-admin/src/main/java/org/orury/admin/post/application/PostServiceImpl.java
  orury-admin/src/main/java/org/orury/admin/user/UserServiceImpl.java
  orury-client/src/main/java/org/orury/client/comment/application/CommentServiceImpl.java
  orury-client/src/main/java/org/orury/client/gym/application/GymServiceImpl.java
  orury-client/src/main/java/org/orury/client/post/application/PostServiceImpl.java
  orury-client/src/main/java/org/orury/client/review/application/ReviewServiceImpl.java
  orury-client/src/main/java/org/orury/client/user/application/UserServiceImpl.java
  orury-client/src/main/resources/application.yml
  orury-client/src/test/java/org/orury/client/comment/application/CommentServiceImplTest.java
  orury-client/src/test/java/org/orury/client/gym/application/GymServiceImplTest.java
  orury-client/src/test/java/org/orury/client/post/service/PostServiceTest.java
  orury-client/src/test/java/org/orury/client/review/application/ReviewServiceImplTest.java
  orury-client/src/test/java/org/orury/client/user/application/UserServiceImplTest.java
  orury-common/src/main/java/org/orury/common/config/BeanUtils.java
  orury-common/src/main/java/org/orury/common/util/ImageUtil.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/entity/Crew.java
  orury-domain/src/main/java/org/orury/domain/global/image/ImageReader.java
  orury-domain/src/main/java/org/orury/domain/global/image/ImageStore.java
  orury-domain/src/main/java/org/orury/domain/global/listener/CrewImageConverter.java
  orury-domain/src/main/java/org/orury/domain/global/listener/EntityImageConverter.java
  orury-domain/src/main/java/org/orury/domain/global/listener/EntityImagesConverter.java
  orury-domain/src/main/java/org/orury/domain/global/listener/GymImagesConverter.java
  orury-domain/src/main/java/org/orury/domain/global/listener/PostImagesConverter.java
  orury-domain/src/main/java/org/orury/domain/global/listener/ReviewImagesConverter.java
  orury-domain/src/main/java/org/orury/domain/global/listener/UserProfileConverter.java
  orury-domain/src/main/java/org/orury/domain/gym/domain/entity/Gym.java
  orury-domain/src/main/java/org/orury/domain/post/domain/dto/PostDto.java
  orury-domain/src/main/java/org/orury/domain/post/domain/entity/Post.java
  orury-domain/src/main/java/org/orury/domain/post/infrastructure/ImageReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/post/infrastructure/ImageStoreImpl.java
  orury-domain/src/main/java/org/orury/domain/review/domain/entity/Review.java
  orury-domain/src/main/java/org/orury/domain/user/domain/dto/UserDto.java
  orury-domain/src/main/java/org/orury/domain/user/domain/entity/User.java
Labels: 🌏 Deploy, 💻 BE

#361 stage merge into main
  orury-admin/src/main/java/org/orury/admin/post/application/PostServiceImpl.java
  orury-admin/src/main/java/org/orury/admin/user/UserServiceImpl.java
  orury-client/src/main/java/org/orury/client/comment/application/CommentServiceImpl.java
  orury-client/src/main/java/org/orury/client/gym/application/GymServiceImpl.java
  orury-client/src/main/java/org/orury/client/post/application/PostServiceImpl.java
  orury-client/src/main/java/org/orury/client/review/application/ReviewServiceImpl.java
  orury-client/src/main/java/org/orury/client/user/application/UserServiceImpl.java
  orury-client/src/main/resources/application.yml
  orury-client/src/test/java/org/orury/client/comment/application/CommentServiceImplTest.java
  orury-client/src/test/java/org/orury/client/gym/application/GymServiceImplTest.java
  orury-client/src/test/java/org/orury/client/post/service/PostServiceTest.java
  orury-client/src/test/java/org/orury/client/review/application/ReviewServiceImplTest.java
  orury-client/src/test/java/org/orury/client/user/application/UserServiceImplTest.java
  orury-common/src/main/java/org/orury/common/config/BeanUtils.java
  orury-common/src/main/java/org/orury/common/util/ImageUtil.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/entity/Crew.java
  orury-domain/src/main/java/org/orury/domain/global/image/ImageReader.java
  orury-domain/src/main/java/org/orury/domain/global/image/ImageStore.java
  orury-domain/src/main/java/org/orury/domain/global/listener/CrewImageConverter.java
  orury-domain/src/main/java/org/orury/domain/global/listener/EntityImageConverter.java
  orury-domain/src/main/java/org/orury/domain/global/listener/EntityImagesConverter.java
  orury-domain/src/main/java/org/orury/domain/global/listener/GymImagesConverter.java
  orury-domain/src/main/java/org/orury/domain/global/listener/PostImagesConverter.java
  orury-domain/src/main/java/org/orury/domain/global/listener/ReviewImagesConverter.java
  orury-domain/src/main/java/org/orury/domain/global/listener/UserProfileConverter.java
  orury-domain/src/main/java/org/orury/domain/gym/domain/entity/Gym.java
  orury-domain/src/main/java/org/orury/domain/post/domain/dto/PostDto.java
  orury-domain/src/main/java/org/orury/domain/post/domain/entity/Post.java
  orury-domain/src/main/java/org/orury/domain/post/infrastructure/ImageReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/post/infrastructure/ImageStoreImpl.java
  orury-domain/src/main/java/org/orury/domain/review/domain/entity/Review.java
  orury-domain/src/main/java/org/orury/domain/user/domain/dto/UserDto.java
  orury-domain/src/main/java/org/orury/domain/user/domain/entity/User.java
Labels: 🌏 Deploy, 💻 BE

#363 Fix : images null check error 수정
  orury-client/src/main/java/org/orury/client/gym/interfaces/response/GymsResponse.java
  orury-client/src/main/java/org/orury/client/post/interfaces/response/PostsResponse.java
  orury-client/src/main/java/org/orury/client/user/interfaces/response/MyPostResponse.java
Labels: 🐞 Fix, 💻 BE

#365 Fix : cors 예외처리
  orury-client/src/main/java/org/orury/client/global/config/SecurityConfig.java
Labels: 🐞 Fix, 💻 BE

#366 Fix : 회원가입 시, UserStatus Enable로 설정하고 saveAndFlush()
  orury-client/src/main/java/org/orury/client/auth/interfaces/request/SignUpRequest.java
Labels: 🐞 Fix, 💻 BE

#368 Chore : 이미지 저장 시 "[]" 로 처리
  orury-domain/src/main/java/org/orury/domain/global/listener/EntityImagesConverter.java
  orury-domain/src/main/java/org/orury/domain/post/infrastructure/ImageStoreImpl.java
Labels: 💻 BE, 🔨 Refactor

#372 feat: 운영 DB 정보 yml 파일 추가
  orury-client/src/main/resources/application-prod.yml
Labels: ⚙️Settings, 💻 BE

#378 Feat : 크루 생성&이미지변경 API 구현
  orury-client/src/main/java/org/orury/client/crew/application/CrewFacade.java
  orury-client/src/main/java/org/orury/client/crew/application/CrewService.java
  orury-client/src/main/java/org/orury/client/crew/application/CrewServiceImpl.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/CrewController.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/message/CrewMessage.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/request/CrewCreateRequest.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/response/CrewResponse.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/response/CrewsResponseByMyCrew.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/response/CrewsResponseByRank.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/response/CrewsResponseByRecommend.java
  orury-client/src/main/java/org/orury/client/review/application/ReviewServiceImpl.java
  orury-common/src/main/java/org/orury/common/error/code/CrewErrorCode.java
  orury-common/src/main/java/org/orury/common/error/exception/GlobalExceptionHandler.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/CrewMemberReader.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/CrewMemberStore.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/CrewStore.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/CrewTagReader.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/CrewTagStore.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/dto/CrewApplicationDto.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/dto/CrewDto.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/dto/CrewGender.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/dto/CrewGenderConverter.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/dto/CrewStatus.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/dto/CrewStatusConverter.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/entity/Crew.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/entity/CrewApplication.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/entity/CrewTag.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewMemberReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewMemberRepository.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewMemberStoreImpl.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewRepository.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewStoreImpl.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewTagReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewTagRepository.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewTagStoreImpl.java
  orury-domain/src/main/java/org/orury/domain/global/constants/NumberConstants.java
  orury-domain/src/main/java/org/orury/domain/global/domain/Region.java
  orury-domain/src/main/java/org/orury/domain/global/domain/RegionConverter.java
  orury-domain/src/main/java/org/orury/domain/global/validation/EnumValidator.java
  orury-domain/src/main/java/org/orury/domain/global/validation/EnumValue.java
  orury-domain/src/main/java/org/orury/domain/post/infrastructure/PostReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/review/infrastructure/ReviewRepository.java
  orury-domain/src/main/resources/db/migration/V1.0.26__modify_crew_table_&_add_crew_tag_table.sql
  orury-domain/src/main/resources/db/migration/V1.0.27__modify_crew_status_column.sql
  orury-domain/src/main/resources/db/migration/V1.0.28__modify_crew_application_table.sql
Labels: 🛢 DB, 💻 BE, ✨ Feature, 🔨 Refactor

#382 Settings : 애플 로그인 client-id 변경
  orury-client/src/main/resources/application.yml
Labels: ⚙️Settings, 💻 BE

#380 Refactor : Image 수정/삭제 비동기 처리
  orury-client/src/main/java/org/orury/client/global/config/AsyncConfig.java
  orury-client/src/main/java/org/orury/client/global/image/ImageAsyncStore.java
  orury-client/src/main/java/org/orury/client/post/application/PostServiceImpl.java
  orury-client/src/main/java/org/orury/client/review/application/ReviewServiceImpl.java
  orury-client/src/main/java/org/orury/client/user/application/UserServiceImpl.java
  orury-client/src/test/java/org/orury/client/post/service/PostServiceTest.java
  orury-client/src/test/java/org/orury/client/review/application/ReviewServiceImplTest.java
  orury-client/src/test/java/org/orury/client/user/application/UserServiceImplTest.java
  orury-domain/src/main/java/org/orury/domain/global/domain/ImageUtils.java
  orury-domain/src/main/java/org/orury/domain/global/image/ImageStore.java
  orury-domain/src/main/java/org/orury/domain/global/infrastructure/S3Repository.java
  orury-domain/src/main/java/org/orury/domain/post/infrastructure/ImageStoreImpl.java
  orury-domain/src/main/java/org/orury/domain/post/infrastructure/PostStoreImpl.java
Labels: 💻 BE, 🔨 Refactor

#385 Refactor : 크루목록 조회 고도화
  orury-client/src/main/java/org/orury/client/crew/application/CrewFacade.java
  orury-client/src/main/java/org/orury/client/crew/application/CrewService.java
  orury-client/src/main/java/org/orury/client/crew/application/CrewServiceImpl.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/CrewController.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/response/CrewsResponse.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/response/CrewsResponseByRank.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/response/CrewsResponseByRecommend.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/CrewMemberReader.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewMemberReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewMemberRepository.java
  orury-domain/src/main/java/org/orury/domain/global/constants/NumberConstants.java
Labels: 💻 BE, 🔨 Refactor

#386 Feat : 크루 관련 API 구현
  orury-client/src/main/java/org/orury/client/crew/application/CrewFacade.java
  orury-client/src/main/java/org/orury/client/crew/application/CrewService.java
  orury-client/src/main/java/org/orury/client/crew/application/CrewServiceImpl.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/CrewController.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/message/CrewMessage.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/request/CrewRequest.java
  orury-client/src/main/java/org/orury/client/meeting/application/MeetingServiceImpl.java
  orury-client/src/test/java/org/orury/client/crew/application/CrewFacadeTest.java
  orury-client/src/test/java/org/orury/client/crew/application/CrewServiceImplTest.java
  orury-client/src/test/java/org/orury/client/meeting/application/MeetingFacadeTest.java
  orury-client/src/test/java/org/orury/client/meeting/application/MeetingServiceImplTest.java
  orury-common/src/main/java/org/orury/common/error/code/CrewErrorCode.java
  orury-common/src/main/java/org/orury/common/util/AgeUtils.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/CrewApplicationReader.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/CrewApplicationStore.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/CrewMemberReader.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/CrewMemberStore.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/CrewReader.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/CrewStore.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/CrewTagStore.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/dto/CrewApplicationDto.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/dto/CrewGender.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewApplicationReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewApplicationRepository.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewApplicationStoreImpl.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewMemberReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewMemberRepository.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewMemberStoreImpl.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewStoreImpl.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewTagRepository.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewTagStoreImpl.java
  orury-domain/src/main/java/org/orury/domain/global/constants/NumberConstants.java
  orury-domain/src/main/java/org/orury/domain/meeting/domain/MeetingMemberStore.java
  orury-domain/src/main/java/org/orury/domain/meeting/domain/MeetingStore.java
  orury-domain/src/main/java/org/orury/domain/meeting/infrastructure/MeetingMemberReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/meeting/infrastructure/MeetingMemberRepository.java
  orury-domain/src/main/java/org/orury/domain/meeting/infrastructure/MeetingMemberStoreImpl.java
  orury-domain/src/main/java/org/orury/domain/meeting/infrastructure/MeetingRepository.java
  orury-domain/src/main/java/org/orury/domain/meeting/infrastructure/MeetingStoreImpl.java
  orury-domain/src/test/java/org/orury/domain/meeting/infrastructure/MeetingMemberReaderImplTest.java
  orury-domain/src/test/java/org/orury/domain/meeting/infrastructure/MeetingMemberStoreImplTest.java
  orury-domain/src/test/java/org/orury/domain/meeting/infrastructure/MeetingReaderImplTest.java
  orury-domain/src/test/java/org/orury/domain/meeting/infrastructure/MeetingStoreImplTest.java
Labels: 💻 BE, ✨ Feature

#388 Feat : SSE 알림 초기 구현
  orury-client/src/main/java/org/orury/client/comment/application/CommentFacade.java
  orury-client/src/main/java/org/orury/client/crew/application/CrewFacade.java
  orury-client/src/main/java/org/orury/client/notification/application/NotificationFacade.java
  orury-client/src/main/java/org/orury/client/notification/application/NotificationService.java
  orury-client/src/main/java/org/orury/client/notification/application/NotificationServiceImpl.java
  orury-client/src/main/java/org/orury/client/notification/interfaces/NotificationController.java
  orury-client/src/main/java/org/orury/client/notification/interfaces/message/NotificationMessage.java
  orury-client/src/main/java/org/orury/client/notification/interfaces/response/NotificationResponse.java
  orury-client/src/test/java/org/orury/client/comment/application/CommentFacadeTest.java
  orury-common/src/main/java/org/orury/common/error/code/NotificationErrorCode.java
  orury-common/src/main/java/org/orury/common/error/code/SseErrorCode.java
  orury-common/src/main/java/org/orury/common/error/exception/SseException.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/CrewMemberReader.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewMemberReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/global/constants/NumberConstants.java
  orury-domain/src/main/java/org/orury/domain/notification/domain/dto/NotificationDto.java
  orury-domain/src/main/java/org/orury/domain/notification/domain/entity/Notification.java
  orury-domain/src/main/java/org/orury/domain/notification/infrastructure/EmitterRepository.java
  orury-domain/src/main/java/org/orury/domain/notification/infrastructure/EmitterRepositoryImpl.java
  orury-domain/src/main/java/org/orury/domain/notification/infrastructure/NotificationRepository.java
  orury-domain/src/main/resources/db/migration/V1.0.29__create_notificaton_table.sql
  orury-domain/src/main/resources/db/migration/V1.0.30__add_content_to_notification_table.sql
  orury-domain/src/main/resources/db/migration/V1.0.31__add_title_to_notification_table.sql
Labels: 💻 BE, ✨ Feature

#391 Feat : 테스트코드 Fixture 생성 메서드 통합 (w/ Object Mother 패턴, Test Fixtures 플러그인)
  orury-client/build.gradle
  orury-client/src/test/java/org/orury/client/crew/application/CrewServiceImplTest.java
  orury-domain/build.gradle
  orury-domain/src/testFixtures/java/org/orury/domain/DomainFixtureFactory.java
Labels: 💻 BE, ✨ Feature, ✅ Test, 🔨 Refactor

#394 Test : Base 테스트 코드 클래스 작성
  orury-client/src/test/java/org/orury/client/auth/application/AuthFacadeTest.java
  orury-client/src/test/java/org/orury/client/auth/application/AuthServiceImplTest.java
  orury-client/src/test/java/org/orury/client/auth/application/KakaoOAuthServiceTest.java
  orury-client/src/test/java/org/orury/client/comment/application/CommentFacadeTest.java
  orury-client/src/test/java/org/orury/client/comment/application/CommentServiceImplTest.java
  orury-client/src/test/java/org/orury/client/config/FacadeTest.java
  orury-client/src/test/java/org/orury/client/config/ServiceTest.java
  orury-client/src/test/java/org/orury/client/crew/application/CrewFacadeTest.java
  orury-client/src/test/java/org/orury/client/gym/application/GymFacadeTest.java
  orury-client/src/test/java/org/orury/client/gym/application/GymServiceImplTest.java
  orury-client/src/test/java/org/orury/client/meeting/application/MeetingFacadeTest.java
  orury-client/src/test/java/org/orury/client/meeting/application/MeetingServiceImplTest.java
  orury-client/src/test/java/org/orury/client/post/service/PostServiceTest.java
  orury-client/src/test/java/org/orury/client/review/application/ReviewFacadeTest.java
  orury-client/src/test/java/org/orury/client/review/application/ReviewServiceImplTest.java
  orury-client/src/test/java/org/orury/client/user/application/UserFacadeTest.java
  orury-client/src/test/java/org/orury/client/user/application/UserServiceImplTest.java
  orury-domain/src/test/java/org/orury/domain/comment/infrastructure/CommentReaderImplTest.java
  orury-domain/src/test/java/org/orury/domain/comment/infrastructure/CommentStoreImplTest.java
  orury-domain/src/test/java/org/orury/domain/config/InfrastructureTest.java
  orury-domain/src/test/java/org/orury/domain/gym/infrastructure/GymReaderImplTest.java
  orury-domain/src/test/java/org/orury/domain/gym/infrastructure/GymStoreImplTest.java
  orury-domain/src/test/java/org/orury/domain/notice/db/repository/NoticeRepositoryTest.java
  orury-domain/src/test/java/org/orury/domain/review/infrastructure/ReviewReaderImplTest.java
  orury-domain/src/test/java/org/orury/domain/review/infrastructure/ReviewStoreImplTest.java
  orury-domain/src/test/java/org/orury/domain/user/infrastructure/UserReaderImplTest.java
  orury-domain/src/test/java/org/orury/domain/user/infrastructure/UserStoreImplTest.java
Labels: 💻 BE, ✅ Test

#397 Test : Test Fixture 생성 코드 통합
  orury-batch/build.gradle
  orury-batch/src/test/java/org/orury/batch/BatchFixtureFactory.java
  orury-batch/src/test/java/org/orury/batch/job/StepItemTest.java
  orury-client/build.gradle
  orury-client/src/main/java/org/orury/client/crew/application/CrewServiceImpl.java
  orury-client/src/test/java/org/orury/client/ClientFixtureFactory.java
  orury-client/src/test/java/org/orury/client/auth/application/AuthFacadeTest.java
  orury-client/src/test/java/org/orury/client/auth/application/AuthServiceImplTest.java
  orury-client/src/test/java/org/orury/client/auth/application/KakaoOAuthServiceTest.java
  orury-client/src/test/java/org/orury/client/comment/application/CommentFacadeTest.java
  orury-client/src/test/java/org/orury/client/comment/application/CommentServiceImplTest.java
  orury-client/src/test/java/org/orury/client/crew/application/CrewFacadeTest.java
  orury-client/src/test/java/org/orury/client/crew/application/CrewServiceImplTest.java
  orury-client/src/test/java/org/orury/client/gym/application/GymFacadeTest.java
  orury-client/src/test/java/org/orury/client/gym/application/GymServiceImplTest.java
  orury-client/src/test/java/org/orury/client/meeting/application/MeetingFacadeTest.java
  orury-client/src/test/java/org/orury/client/meeting/application/MeetingServiceImplTest.java
  orury-client/src/test/java/org/orury/client/post/application/PostServiceImplTest.java
  orury-client/src/test/java/org/orury/client/post/controller/PostControllerTest.java
  orury-client/src/test/java/org/orury/client/post/controller/PostLikeControllerTest.java
  orury-client/src/test/java/org/orury/client/review/application/ReviewFacadeTest.java
  orury-client/src/test/java/org/orury/client/review/application/ReviewServiceImplTest.java
  orury-client/src/test/java/org/orury/client/review/controller/ReviewControllerTest.java
  orury-client/src/test/java/org/orury/client/review/controller/ReviewReactionControllerTest.java
  orury-client/src/test/java/org/orury/client/review/service/ReviewReactionServiceTest.java
  orury-client/src/test/java/org/orury/client/review/service/ReviewServiceTest.java
  orury-client/src/test/java/org/orury/client/user/application/UserFacadeTest.java
  orury-client/src/test/java/org/orury/client/user/application/UserServiceImplTest.java
  orury-client/src/test/java/org/orury/client/user/controller/UserControllerTest.java
  orury-client/src/test/java/org/orury/client/user/service/UserServiceTest.java
  orury-domain/src/main/java/org/orury/domain/gym/domain/dto/GymDto.java
  orury-domain/src/main/java/org/orury/domain/gym/domain/entity/Gym.java
  orury-domain/src/test/java/org/orury/domain/comment/infrastructure/CommentReaderImplTest.java
  orury-domain/src/test/java/org/orury/domain/comment/infrastructure/CommentStoreImplTest.java
  orury-domain/src/test/java/org/orury/domain/config/TestRepositoryUtils.java
  orury-domain/src/test/java/org/orury/domain/gym/infrastructure/GymReaderImplTest.java
  orury-domain/src/test/java/org/orury/domain/gym/infrastructure/GymStoreImplTest.java
  orury-domain/src/test/java/org/orury/domain/meeting/infrastructure/MeetingMemberStoreImplTest.java
  orury-domain/src/test/java/org/orury/domain/notice/db/repository/NoticeRepositoryTest.java
  orury-domain/src/test/java/org/orury/domain/review/infrastructure/ReviewReaderImplTest.java
  orury-domain/src/test/java/org/orury/domain/review/infrastructure/ReviewStoreImplTest.java
  orury-domain/src/test/java/org/orury/domain/user/infrastructure/UserReaderImplTest.java
  orury-domain/src/test/java/org/orury/domain/user/infrastructure/UserStoreImplTest.java
  orury-domain/src/testFixtures/java/org/orury/domain/AdminDomainFixture.java
  orury-domain/src/testFixtures/java/org/orury/domain/AuthDomainFixture.java
  orury-domain/src/testFixtures/java/org/orury/domain/CommentDomainFixture.java
  orury-domain/src/testFixtures/java/org/orury/domain/CrewDomainFixture.java
  orury-domain/src/testFixtures/java/org/orury/domain/GymDomainFixture.java
  orury-domain/src/testFixtures/java/org/orury/domain/MeetingDomainFixture.java
  orury-domain/src/testFixtures/java/org/orury/domain/PostDomainFixture.java
  orury-domain/src/testFixtures/java/org/orury/domain/ReviewDomainFixture.java
  orury-domain/src/testFixtures/java/org/orury/domain/UserDomainFixture.java
Labels: 💻 BE, ✅ Test, 🔨 Refactor

#399 Refactor : 크루 Validating 클래스 작성
  orury-client/src/main/java/org/orury/client/crew/application/CrewServiceImpl.java
  orury-client/src/main/java/org/orury/client/crew/application/policy/CrewApplicationPolicy.java
  orury-client/src/main/java/org/orury/client/crew/application/policy/CrewCreatePolicy.java
  orury-client/src/main/java/org/orury/client/crew/application/policy/CrewPolicy.java
  orury-client/src/main/java/org/orury/client/crew/application/policy/CrewUpdatePolicy.java
  orury-client/src/test/java/org/orury/client/config/ServiceTest.java
  orury-client/src/test/java/org/orury/client/crew/application/CrewServiceImplTest.java
  orury-client/src/test/java/org/orury/client/crew/application/policy/CrewApplicationPolicyTest.java
  orury-client/src/test/java/org/orury/client/crew/application/policy/CrewCreatePolicyTest.java
  orury-client/src/test/java/org/orury/client/crew/application/policy/CrewUpdatePolicyTest.java
  orury-domain/src/testFixtures/java/org/orury/domain/CrewDomainFixture.java
Labels: 💻 BE, ✅ Test, 🔨 Refactor

#401 Refactor : 이미지 비동기 처리 리팩토링 (ImageAsyncStore 삭제)
  orury-client/src/main/java/org/orury/client/crew/application/CrewServiceImpl.java
  orury-client/src/main/java/org/orury/client/global/config/AsyncConfig.java
  orury-client/src/main/java/org/orury/client/global/image/ImageAsyncStore.java
  orury-client/src/main/java/org/orury/client/post/application/PostServiceImpl.java
  orury-client/src/main/java/org/orury/client/review/application/ReviewServiceImpl.java
  orury-client/src/main/java/org/orury/client/user/application/UserServiceImpl.java
  orury-client/src/test/java/org/orury/client/config/ServiceTest.java
  orury-client/src/test/java/org/orury/client/crew/application/CrewServiceImplTest.java
  orury-client/src/test/java/org/orury/client/post/application/PostServiceImplTest.java
  orury-client/src/test/java/org/orury/client/user/application/UserServiceImplTest.java
  orury-domain/src/main/java/org/orury/domain/global/image/ImageStore.java
  orury-domain/src/main/java/org/orury/domain/post/infrastructure/ImageStoreImpl.java
Labels: 💻 BE, 🔨 Refactor

#403 Test : Domain모듈 Reader/Store 테스트코드 보완
  orury-client/build.gradle
  orury-domain/build.gradle
  orury-domain/src/test/java/org/orury/domain/auth/infrastructure/RefreshTokenReaderImplTest.java
  orury-domain/src/test/java/org/orury/domain/auth/infrastructure/RefreshTokenStoreImplTest.java
  orury-domain/src/test/java/org/orury/domain/crew/infrastructure/CrewApplicationReaderImplTest.java
  orury-domain/src/test/java/org/orury/domain/crew/infrastructure/CrewApplicationStoreImplTest.java
  orury-domain/src/test/java/org/orury/domain/crew/infrastructure/CrewMemberReaderImplTest.java
  orury-domain/src/test/java/org/orury/domain/crew/infrastructure/CrewMemberStoreImplTest.java
  orury-domain/src/test/java/org/orury/domain/crew/infrastructure/CrewReaderImplTest.java
  orury-domain/src/test/java/org/orury/domain/crew/infrastructure/CrewStoreImplTest.java
  orury-domain/src/test/java/org/orury/domain/crew/infrastructure/CrewTagReaderImplTest.java
  orury-domain/src/test/java/org/orury/domain/crew/infrastructure/CrewTagStoreImplTest.java
  orury-domain/src/test/java/org/orury/domain/gym/infrastructure/GymReaderImplTest.java
  orury-domain/src/test/java/org/orury/domain/notice/infrastructure/NoticeReaderImplTest.java
  orury-domain/src/test/java/org/orury/domain/notice/infrastructure/NoticeStoreImplTest.java
  orury-domain/src/test/java/org/orury/domain/user/infrastructure/UserReaderImplTest.java
  orury-domain/src/test/java/org/orury/domain/user/infrastructure/UserStoreImplTest.java
  orury-domain/src/testFixtures/java/org/orury/domain/CrewDomainFixture.java
Labels: 💻 BE, ✅ Test

#405 Feat : 크루 상세 조회 시 크루 가입 질문 추가 전달
  orury-client/src/main/java/org/orury/client/auth/application/jwt/JwtTokenServiceImpl.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/response/CrewResponse.java
Labels: 💻 BE, 📬 API, ✨ Feature

#411 Feat : 암장 타입 정보 추가 전달 및 운영시간 요일 한글로 변경
  orury-batch/src/main/java/org/orury/batch/dto/GymResponse.java
  orury-client/src/main/java/org/orury/client/gym/interfaces/response/GymResponse.java
  orury-common/src/main/java/org/orury/common/error/code/GymErrorCode.java
  orury-domain/src/main/java/org/orury/domain/gym/domain/dto/GymDto.java
  orury-domain/src/main/java/org/orury/domain/gym/domain/dto/GymType.java
  orury-domain/src/main/java/org/orury/domain/gym/domain/dto/GymTypeConverter.java
  orury-domain/src/main/java/org/orury/domain/gym/domain/entity/Gym.java
  orury-domain/src/main/resources/db/migration/V1.0.32__add_gym_type_column.sql
  orury-domain/src/testFixtures/java/org/orury/domain/GymDomainFixture.java
Labels: 💻 BE, 📬 API, ✨ Feature
