Repository Kernel360/f1-Orury-Backend, pull requests merged in 2024-04, with the labels that each got.

#410 Refactor: SSE 알람 관련 프론트 요구사항 반영
  orury-client/src/main/java/org/orury/client/notification/interfaces/response/NotificationResponse.java
Labels: 💻 BE, 📬 API, 🔨 Refactor

#407 Refactor : image 패키지 생성 & 프론트 요구사항 반영
  orury-admin/src/main/java/org/orury/admin/post/application/PostServiceImpl.java
  orury-client/src/main/java/org/orury/client/crew/application/CrewFacade.java
  orury-client/src/main/java/org/orury/client/crew/application/CrewService.java
  orury-client/src/main/java/org/orury/client/crew/application/CrewServiceImpl.java
  orury-client/src/main/java/org/orury/client/crew/application/policy/CrewApplicationPolicy.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/CrewController.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/message/CrewMessage.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/request/CrewRequest.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/response/CrewMembersResponse.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/response/CrewResponse.java
  orury-client/src/main/java/org/orury/client/meeting/application/MeetingServiceImpl.java
  orury-client/src/main/java/org/orury/client/post/application/PostServiceImpl.java
  orury-client/src/main/java/org/orury/client/review/application/ReviewServiceImpl.java
  orury-client/src/main/java/org/orury/client/user/application/UserServiceImpl.java
  orury-client/src/main/resources/application.yml
  orury-client/src/test/java/org/orury/client/OruryClientApplicationTest.java
  orury-client/src/test/java/org/orury/client/config/ServiceTest.java
  orury-client/src/test/java/org/orury/client/crew/application/CrewFacadeTest.java
  orury-client/src/test/java/org/orury/client/crew/application/CrewServiceImplTest.java
  orury-client/src/test/java/org/orury/client/crew/application/policy/CrewApplicationPolicyTest.java
  orury-client/src/test/java/org/orury/client/meeting/application/MeetingServiceImplTest.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/CrewMemberReader.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewMemberReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/global/constants/NumberConstants.java
  orury-domain/src/main/java/org/orury/domain/global/listener/EntityImageConverter.java
  orury-domain/src/main/java/org/orury/domain/global/listener/EntityImagesConverter.java
  orury-domain/src/main/java/org/orury/domain/image/domain/ImageReader.java
  orury-domain/src/main/java/org/orury/domain/image/domain/ImageStore.java
  orury-domain/src/main/java/org/orury/domain/image/infrastructure/ImageReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/image/infrastructure/ImageStoreImpl.java
  orury-domain/src/main/java/org/orury/domain/meeting/domain/MeetingMemberReader.java
  orury-domain/src/main/java/org/orury/domain/meeting/infrastructure/MeetingMemberReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/post/infrastructure/PostStoreImpl.java
  orury-domain/src/test/java/org/orury/domain/config/InfrastructureTest.java
  orury-domain/src/test/java/org/orury/domain/crew/infrastructure/CrewMemberReaderImplTest.java
  orury-domain/src/test/java/org/orury/domain/meeting/infrastructure/MeetingMemberReaderImplTest.java
Labels: 🎸Chore, 💻 BE, 🔨 Refactor

#418 Refactor : GET요청 RequestParam으로 수정
  orury-client/src/main/java/org/orury/client/gym/interfaces/GymController.java
  orury-client/src/main/java/org/orury/client/gym/interfaces/request/AreaGrid.java
  orury-client/src/main/java/org/orury/client/gym/interfaces/request/GymAreaRequest.java
  orury-domain/src/main/java/org/orury/domain/gym/domain/dto/GymType.java
Labels: 🎸Chore, 💻 BE, 📬 API, 🔨 Refactor

#419 이미지 로직 수정 (테스트 목적으로 POST만 임시 적용)
  orury-client/src/main/java/org/orury/client/post/interfaces/response/PostsResponse.java
  orury-common/src/main/java/org/orury/common/util/ImageUtil.java
  orury-common/src/main/java/org/orury/common/util/S3Folder.java
  orury-domain/build.gradle
  orury-domain/src/main/java/org/orury/domain/global/listener/EntityImagesConverter.java
  orury-domain/src/main/java/org/orury/domain/image/infrastructure/ImageStoreImpl.java
Labels: 💻 BE, 🔨 Refactor

#422 이미지 로직 리팩터링
  orury-client/src/main/java/org/orury/client/post/interfaces/response/PostsResponse.java
  orury-common/src/main/java/org/orury/common/util/ImageUtil.java
  orury-domain/build.gradle
  orury-domain/src/main/java/org/orury/domain/global/listener/EntityImagesConverter.java
  orury-domain/src/main/java/org/orury/domain/image/infrastructure/ImageStoreImpl.java
Labels: 💻 BE, 🔨 Refactor

#421 Feat : (가입한/가입신청한) 내 크루 목록 조회 API 구현
  orury-client/src/main/java/org/orury/client/crew/application/CrewFacade.java
  orury-client/src/main/java/org/orury/client/crew/application/CrewService.java
  orury-client/src/main/java/org/orury/client/crew/application/CrewServiceImpl.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/CrewController.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/response/CrewsResponse.java
  orury-client/src/test/java/org/orury/client/config/ServiceTest.java
  orury-client/src/test/java/org/orury/client/crew/application/CrewFacadeTest.java
  orury-client/src/test/java/org/orury/client/crew/application/CrewServiceImplTest.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/CrewApplicationReader.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/CrewMemberReader.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/CrewReader.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewApplicationReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewApplicationRepository.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewMemberReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewMemberRepository.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewRepository.java
  orury-domain/src/test/java/org/orury/domain/config/InfrastructureTest.java
  orury-domain/src/test/java/org/orury/domain/crew/infrastructure/CrewApplicationReaderImplTest.java
  orury-domain/src/test/java/org/orury/domain/crew/infrastructure/CrewMemberReaderImplTest.java
  orury-domain/src/test/java/org/orury/domain/crew/infrastructure/CrewReaderImplTest.java
Labels: 💻 BE, ✨ Feature

#429 Feat : 상세화면에 크루장 여부값 추가
  orury-client/src/main/java/org/orury/client/crew/application/CrewFacade.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/response/CrewResponse.java
Labels: 💻 BE, 📬 API, ✨ Feature

#424 Refactor : 크루 region 값 string to list
  orury-client/src/main/java/org/orury/client/crew/interfaces/request/CrewRequest.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/response/CrewResponse.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/response/CrewsResponse.java
  orury-client/src/test/java/org/orury/client/ClientFixtureFactory.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/dto/CrewDto.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/entity/Crew.java
  orury-domain/src/main/java/org/orury/domain/global/domain/RegionConverter.java
  orury-domain/src/main/java/org/orury/domain/global/validation/EnumValues.java
  orury-domain/src/main/java/org/orury/domain/global/validation/EnumsValidator.java
  orury-domain/src/main/resources/db/migration/V1.0.33__modify_region_column_name.sql
  orury-domain/src/testFixtures/java/org/orury/domain/CrewDomainFixture.java
Labels: 💻 BE, 📬 API, 🔨 Refactor

#427 Feat : 크루장용 크루지원자 목록 조회 API 구현
  orury-client/src/main/java/org/orury/client/crew/application/CrewFacade.java
  orury-client/src/main/java/org/orury/client/crew/application/CrewService.java
  orury-client/src/main/java/org/orury/client/crew/application/CrewServiceImpl.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/CrewController.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/message/CrewMessage.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/response/CrewApplicantsResponse.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/response/CrewsResponse.java
  orury-client/src/test/java/org/orury/client/crew/application/CrewFacadeTest.java
  orury-client/src/test/java/org/orury/client/crew/application/CrewServiceImplTest.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/CrewApplicationReader.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/dto/CrewApplicationDto.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewApplicationReaderImpl.java
  orury-domain/src/test/java/org/orury/domain/config/InfrastructureTest.java
  orury-domain/src/test/java/org/orury/domain/crew/infrastructure/CrewApplicationReaderImplTest.java
  orury-domain/src/testFixtures/java/org/orury/domain/CrewDomainFixture.java
Labels: 💻 BE, ✨ Feature

#433 Feat : 회원가입 시 유저 지역정보 받아오기
  orury-client/src/main/java/org/orury/client/auth/interfaces/AuthController.java
  orury-client/src/main/java/org/orury/client/auth/interfaces/request/SignUpRequest.java
  orury-client/src/main/java/org/orury/client/user/interfaces/request/UserInfoRequest.java
  orury-domain/src/main/java/org/orury/domain/auth/domain/dto/LoginDto.java
  orury-domain/src/main/java/org/orury/domain/user/domain/dto/UserDto.java
  orury-domain/src/main/java/org/orury/domain/user/domain/entity/User.java
  orury-domain/src/main/resources/db/migration/V1.0.34__add_user_regions_column.sql
  orury-domain/src/test/java/org/orury/domain/comment/infrastructure/CommentStoreImplTest.java
Labels: 💻 BE, ✨ Feature

#436 Fix : 운영시간이 null인 경우 오류 수정 및 요일 정렬 처리
  orury-client/src/main/java/org/orury/client/gym/interfaces/response/GymResponse.java
Labels: 🐞 Fix, 💻 BE

#434 Feat : 크루 목록 정렬(추천순/인기순/활동순/최신순) 구현
  orury-client/src/main/java/org/orury/client/crew/application/CrewFacade.java
  orury-client/src/main/java/org/orury/client/crew/application/CrewService.java
  orury-client/src/main/java/org/orury/client/crew/application/CrewServiceImpl.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/CrewController.java
  orury-client/src/test/java/org/orury/client/crew/application/CrewFacadeTest.java
  orury-client/src/test/java/org/orury/client/crew/application/CrewServiceImplTest.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/CrewReader.java
  orury-domain/src/main/java/org/orury/domain/crew/domain/dto/CrewGender.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/crew/infrastructures/CrewRepository.java
  orury-domain/src/test/java/org/orury/domain/crew/infrastructure/CrewReaderImplTest.java
Labels: 💻 BE, ✨ Feature

#438 Feat : 크루 생성 시, 크루 id 반환
  orury-client/src/main/java/org/orury/client/crew/application/CrewFacade.java
  orury-client/src/main/java/org/orury/client/crew/application/CrewService.java
  orury-client/src/main/java/org/orury/client/crew/application/CrewServiceImpl.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/CrewController.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/request/CrewRequest.java
  orury-client/src/main/java/org/orury/client/crew/interfaces/response/CrewIdResponse.java
  orury-client/src/test/java/org/orury/client/crew/application/CrewFacadeTest.java
Labels: 💻 BE, 🔨 Refactor

#442 Fix : 크루목록 추천순 조회 url path명 변경
  orury-client/src/main/java/org/orury/client/crew/interfaces/CrewController.java
Labels: 🐞 Fix, 💻 BE

#443 Feat : 리뷰 생성/수정/조회 시 암장의 난이도, 상세설명 필드 추가
  orury-client/src/main/java/org/orury/client/review/interfaces/ReviewController.java
  orury-client/src/main/java/org/orury/client/review/interfaces/request/ReviewCreateRequest.java
  orury-client/src/main/java/org/orury/client/review/interfaces/request/ReviewUpdateRequest.java
  orury-client/src/main/java/org/orury/client/review/interfaces/response/ReviewsResponse.java
  orury-common/src/main/java/org/orury/common/error/code/ReviewErrorCode.java
  orury-domain/src/main/java/org/orury/domain/review/domain/dto/Difficulty.java
  orury-domain/src/main/java/org/orury/domain/review/domain/dto/DifficultyConverter.java
  orury-domain/src/main/java/org/orury/domain/review/domain/dto/ReviewDto.java
  orury-domain/src/main/java/org/orury/domain/review/domain/entity/Review.java
  orury-domain/src/main/resources/db/migration/V1.0.35__add_review_columns.sql
  orury-domain/src/testFixtures/java/org/orury/domain/ReviewDomainFixture.java
Labels: 💻 BE, ✨ Feature

#444 Refactor : 리뷰 반응 수정
  orury-client/src/main/java/org/orury/client/review/application/ReviewServiceImpl.java
  orury-client/src/main/java/org/orury/client/review/interfaces/request/ReviewCreateRequest.java
  orury-client/src/main/java/org/orury/client/review/interfaces/request/ReviewUpdateRequest.java
  orury-client/src/main/java/org/orury/client/review/interfaces/response/ReviewsResponse.java
  orury-client/src/main/java/org/orury/client/user/interfaces/response/MyReviewResponse.java
  orury-domain/src/main/java/org/orury/domain/global/constants/NumberConstants.java
  orury-domain/src/main/java/org/orury/domain/review/domain/dto/ReviewDto.java
  orury-domain/src/main/java/org/orury/domain/review/domain/entity/Review.java
  orury-domain/src/main/java/org/orury/domain/review/infrastructure/ReviewRepository.java
  orury-domain/src/main/resources/db/migration/V1.0.36__modify_review_reaction_columns.sql
  orury-domain/src/testFixtures/java/org/orury/domain/ReviewDomainFixture.java
Labels: 💻 BE, 🔨 Refactor

#448 Refactor : 크루 조회에 필요한 값 추가
  orury-client/src/main/java/org/orury/client/crew/interfaces/response/CrewResponse.java
Labels: 💻 BE, 🔨 Refactor
