Repository Kernel360/f1-Orury-Backend, pull requests merged in 2024-01, with the labels that each got.

#82 Fix : Post CRUD 테스트코드 수정
  build.gradle
  orury-client/src/test/java/org/fastcampus/oruryclient/post/service/PostServiceTest.java
Labels: 🐞 Fix, 💻 BE, ✅ Test

#83 Settings : Jasypt 적용
  build.gradle
  orury-client/build.gradle
  orury-client/src/main/java/org/fastcampus/oruryclient/OruryClientApplication.java
  orury-client/src/main/java/org/fastcampus/oruryclient/global/config/JasyptConfig.java
  orury-client/src/main/resources/application.yaml
  orury-client/src/test/java/org/fastcampus/oruryclient/post/service/PostServiceTest.java
Labels: 🌏 Deploy, ⚙️Settings, 💻 BE

#85 Fix : Merge 꼬인 내용 수정
  orury-client/src/test/java/org/fastcampus/oruryclient/post/service/PostServiceTest.java
Labels: 🐞 Fix, 💻 BE

#86 Settings : Github Action 기능 추가
  .github/workflows/gradle.yml
  orury-client/src/test/java/org/fastcampus/oruryclient/post/service/PostServiceTest.java
Labels: ⚙️Settings

#87 Test : CommentServiceTest & CommentLikeServiceTest 추가
  .github/workflows/gradle.yml
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/controller/CommentController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/error/CommentErrorCode.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/service/CommentService.java
  orury-client/src/test/java/org/fastcampus/oruryclient/comment/service/CommentLikeServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/comment/service/CommentServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/post/service/PostLikeServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/post/service/PostServiceTest.java
  orury-common/src/main/java/resources/application.yaml
Labels: 🐞 Fix, 💻 BE, ✅ Test

#91 Settings : CORS 에러 회피 세팅
  orury-client/src/main/java/org/fastcampus/oruryclient/global/config/SecurityConfig.java
Labels: ⚙️Settings, 💻 BE

#92 Feature : Batch 설정(초안 공유용)
  build.gradle
  orury-batch/build.gradle
  orury-batch/settings.gradle
  orury-batch/src/main/java/org/fastcampus/orurybatch/OruryBatchApplication.java
  orury-batch/src/main/java/org/fastcampus/orurybatch/config/JobCompletionNotificationListener.java
  orury-batch/src/main/java/org/fastcampus/orurybatch/config/JpaAuditingConfig.java
  orury-batch/src/main/java/org/fastcampus/orurybatch/job/GymJobConfiguration.java
  orury-batch/src/main/java/org/fastcampus/orurybatch/kakao/KakaoMapClient.java
  orury-batch/src/main/resources/application.yaml
  orury-domain/src/main/java/org/fastcampus/orurydomain/Gym/db/model/Gym.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/Gym/db/repository/GymRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/Gym/dto/GymDto.java
  orury-domain/src/main/resources/db/migration/V1.0.2__create_gym.sql
Labels: ✨ Feature

#98 Feat : AOP 로깅 및 메서드 로깅
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/service/CommentService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/global/error/BusinessException.java
  orury-client/src/main/java/org/fastcampus/oruryclient/global/error/GlobalExceptionHandler.java
  orury-client/src/main/java/org/fastcampus/oruryclient/global/error/dto/ErrorResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/service/PostService.java
  orury-client/src/test/java/org/fastcampus/oruryclient/comment/service/CommentLikeServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/comment/service/CommentServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/post/service/PostServiceTest.java
  orury-common/src/main/java/org/fastcampus/orurycommon/log/LogAspect.java
  orury-common/src/main/java/org/fastcampus/orurycommon/log/LoggerFilter.java
  orury-common/src/main/java/org/fastcampus/orurycommon/log/Logging.java
  orury-domain/src/main/resources/db/migration/V1.0.2__create_gym.sql
Labels: 🐞 Fix, 💻 BE, ✨ Feature

#101 Feature : Auto Code Review for GPT3.5
  .github/workflows/cr.yml
Labels: ⚙️Settings, 💻 BE

#100 Feature : Batch 작업 구현
  orury-batch/build.gradle
  orury-batch/src/main/java/org/fastcampus/orurybatch/OruryBatchApplication.java
  orury-batch/src/main/java/org/fastcampus/orurybatch/client/KakaoMapClient.java
  orury-batch/src/main/java/org/fastcampus/orurybatch/dto/GymResponse.java
  orury-batch/src/main/java/org/fastcampus/orurybatch/dto/KakaoMapGymResponse.java
  orury-batch/src/main/java/org/fastcampus/orurybatch/job/GymItemProcessor.java
  orury-batch/src/main/java/org/fastcampus/orurybatch/job/GymItemReader.java
  orury-batch/src/main/java/org/fastcampus/orurybatch/job/GymJobConfiguration.java
  orury-batch/src/main/java/org/fastcampus/orurybatch/job/GymJobScheduler.java
  orury-batch/src/main/java/org/fastcampus/orurybatch/kakao/KakaoMapClient.java
  orury-batch/src/main/resources/application.yaml
  orury-domain/src/main/java/org/fastcampus/orurydomain/FlywayConfig.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/gym/db/model/Gym.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/gym/db/repository/GymRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/gym/dto/GymDto.java
  orury-domain/src/main/resources/db/migration/V1.0.3__create_batch_tables.sql
  orury-domain/src/main/resources/db/migration/V1.0.4__add_kakaoId_column_gym.sql
  orury-domain/src/main/resources/db/migration/V1.0.5__alter_kakaoId_column_gym.sql
Labels: 💻 BE, ✨ Feature, 💵 GPT REVIEW

#103 Chore : GPT-Reviewer 수정
  .github/workflows/cr.yml
Labels: 💵 GPT REVIEW

#105 Chore : GPT 코드리뷰 테스트
  .github/workflows/cr.yml
Labels: ✅ Test, 💵 GPT REVIEW

#106 로그인 작업을 위한 브랜치 분리
  orury-client/build.gradle
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/controller/AuthController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/converter/request/LoginRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/converter/response/LoginResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/error/AuthErrorCode.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/error/JwtErrorCode.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/filter/CustomAuthFailureHandler.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/filter/CustomAuthSuccessHandler.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/filter/CustomAuthenticationFilter.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/filter/CustomAuthenticationProvider.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/jwt/JwtAuthorizationFilter.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/jwt/JwtTokenInterceptor.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/jwt/TokenUtils.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/service/AuthService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/global/config/SecurityConfig.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/service/CustomUserDetailsService.java
  orury-domain/build.gradle
  orury-domain/src/main/java/org/fastcampus/orurydomain/auth/db/repository/UserRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/auth/dto/Test.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/user/db/repository/UserRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/user/dto/UserPrincipal.java
Labels: ⚙️Settings, 💻 BE

#107 Refactor : 코드리뷰 업데이트
  .github/workflows/cr.yml
Labels: 💻 BE, 💵 GPT REVIEW

#109 Fix : Post(게시글) 삭제 Bug Fix
  orury-client/src/main/java/org/fastcampus/oruryclient/post/service/PostService.java
Labels: 🐞 Fix, 💻 BE

#112 Refactor : GPT 코드리뷰 조건 제거
  .github/workflows/cr.yml
Labels: 💻 BE, 🔨 Refactor

#110 Feature : 리뷰 CRUD 및 서비스 테스트코드
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/service/AuthService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/global/constants/NumberConstants.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/error/GymErrorCode.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/service/GymService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/controller/ReviewController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/request/ReviewCreateRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/request/ReviewUpdateRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/response/ReviewResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/response/ReviewsResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/response/ReviewsWithCursorResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/error/ReviewErrorCode.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/service/ReviewService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/util/ReviewMessage.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/controller/UserController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/response/MypageResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/error/UserErrorCode.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/service/UserService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/util/image/converter/ImageUrlConverter.java
  orury-client/src/test/java/org/fastcampus/oruryclient/auth/service/AuthServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/service/ReviewServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/user/db/model/UserTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/user/db/repository/UserRepositoryTest.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/gym/db/model/Gym.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/gym/db/repository/GymRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/gym/dto/GymDto.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/review/db/model/Review.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/review/db/repository/ReviewRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/review/dto/ReviewDto.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/user/db/model/User.java
  orury-domain/src/main/resources/db/migration/V1.0.6__create_review.sql
Labels: 💻 BE, ✨ Feature, ✅ Test, 🔨 Refactor, 💵 GPT REVIEW

#114 Feat : Jacoco 적용
  orury-client/build.gradle
Labels: ⚙️Settings, 💻 BE

#118 Refactor : Post '검색결과 없음'과 'Pagination 종료'에 대한 cursor 응답 구분
  orury-client/src/main/java/org/fastcampus/oruryclient/global/constants/NumberConstants.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/controller/PostController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/converter/response/PostsWithCursorResponse.java
Labels: 💻 BE, 🔨 Refactor

#122 GPT쨩 코드리뷰 비활성화
  .github/workflows/cr.yml
Labels: ⚙️Settings

#120 Feat : Security + JWT 기반 로그인 1차 Merge
  orury-admin/src/main/java/org/fastcampus/oruryadmin/global/security/jwt/JwtAccessDeniedHandler.java
  orury-admin/src/main/java/org/fastcampus/oruryadmin/global/security/jwt/JwtAuthenticationEntryPoint.java
  orury-client/build.gradle
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/controller/AuthController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/converter/request/LoginRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/converter/request/SignUpRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/converter/response/LoginResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/filter/CustomAuthenticationFilter.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/jwt/JwtToken.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/jwt/JwtTokenFilter.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/jwt/JwtTokenProvider.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/service/AuthService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/global/config/SecurityConfig.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/service/CustomUserDetailsService.java
  orury-client/src/main/resources/application.yaml
  orury-common/src/main/java/org/fastcampus/orurycommon/error/code/JwtErrorCode.java
  orury-domain/build.gradle
  orury-domain/src/main/java/org/fastcampus/orurydomain/auth/db/repository/UserRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/auth/dto/Test.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/user/db/repository/UserRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/user/dto/UserPrincipal.java
  orury-domain/src/main/resources/db/migration/V1.0.7__modify_user_email_unique_key.sql
Labels: 💻 BE, ✨ Feature

#124 Feature : s3 image
  orury-client/src/main/java/org/fastcampus/oruryclient/ImageController.java
  orury-client/src/main/resources/application.yaml
  orury-common/build.gradle
  orury-common/src/main/java/org/fastcampus/orurycommon/s3/S3Config.java
  orury-common/src/main/java/org/fastcampus/orurycommon/s3/S3Service.java
  orury-common/src/main/java/org/fastcampus/orurycommon/s3/Snowflake.java
Labels: 💻 BE, ✨ Feature

#126 Refactor : jasypt config
  .github/workflows/cr.yml
  orury-batch/src/main/resources/application.yaml
  orury-client/src/main/java/org/fastcampus/oruryclient/ImageController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/OruryClientApplication.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/controller/CommentController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/controller/CommentLikeController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/converter/message/CommentMessage.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/service/CommentService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/controller/PostController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/controller/PostLikeController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/converter/message/PostMessage.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/controller/ReviewController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/message/ReviewMessage.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/request/ReviewCreateRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/request/ReviewUpdateRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/response/ReviewResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/response/ReviewsResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/controller/UserController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/message/UserMessage.java
  orury-client/src/main/resources/application.yaml
  orury-common/build.gradle
  orury-common/src/main/java/org/fastcampus/orurycommon/config/FlywayConfig.java
  orury-common/src/main/java/org/fastcampus/orurycommon/config/JasyptConfig.java
  orury-common/src/main/java/org/fastcampus/orurycommon/config/S3Config.java
  orury-common/src/main/java/org/fastcampus/orurycommon/util/ImageUrlConverter.java
  orury-common/src/main/java/org/fastcampus/orurycommon/util/S3Service.java
  orury-common/src/main/java/org/fastcampus/orurycommon/util/Snowflake.java
  orury-domain/build.gradle
Labels: 💻 BE, 🔨 Refactor

#129 Feat&Refactor : Refresh토큰 구현 & CustomAuthenticationFilter 삭제
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/controller/AuthController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/converter/request/LoginRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/converter/response/LoginResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/filter/CustomAuthenticationFilter.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/jwt/JwtTokenFilter.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/jwt/JwtTokenProvider.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/service/AuthService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/util/AuthMessage.java
  orury-client/src/main/java/org/fastcampus/oruryclient/global/config/SecurityConfig.java
  orury-client/src/main/java/org/fastcampus/oruryclient/global/message/info/InfoMessage.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/service/CustomUserDetailsService.java
  orury-common/src/main/java/org/fastcampus/orurycommon/error/code/TokenErrorCode.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/user/dto/UserPrincipal.java
  orury-domain/src/main/resources/db/migration/V1.0.8__drop_refresh_token_table.sql
Labels: 💻 BE, ✨ Feature, 🔨 Refactor

#131 게시판 컨트롤러 테스트 코드
  orury-client/src/main/java/org/fastcampus/oruryclient/post/controller/PostController.java
  orury-client/src/test/java/org/fastcampus/oruryclient/config/ControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/post/controller/PostControllerTest.java
Labels: ✅ Test

#133 Fix : PostLike, CommentLike 삭제 시, RequestBody -> PathVariable로 수정
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/controller/AuthController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/converter/message/AuthMessage.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/controller/CommentLikeController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/converter/request/CommentLikeRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/controller/PostLikeController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/converter/request/PostLikeRequest.java
Labels: 🐞 Fix, 💻 BE

#139 Test : 게시글 좋아요 관련 컨트롤러 테스트
  orury-client/src/test/java/org/fastcampus/oruryclient/post/controller/PostLikeControllerTest.java
Labels: 💻 BE, ✅ Test

#141 Test : 댓글 관련 기능 컨트롤러 테스트 코드
  orury-client/src/test/java/org/fastcampus/oruryclient/comment/controller/CommentControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/post/controller/PostLikeControllerTest.java
Labels: 💻 BE, ✅ Test

#143 Test : 댓글 좋아요 관련 컨트롤러 테스트 코드 작성
  orury-client/src/test/java/org/fastcampus/oruryclient/comment/controller/CommentLikeControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/post/controller/PostLikeControllerTest.java
Labels: 💻 BE, ✅ Test

#138 Feat : ReviewReaction 기능 구현 및 Review 리팩토링
  orury-client/src/main/java/org/fastcampus/oruryclient/global/constants/NumberConstants.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/controller/ReviewController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/controller/ReviewReactionController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/request/ReviewReactionRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/response/ReviewsResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/response/ReviewsWithCursorResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/service/ReviewReactionService.java
  orury-client/src/test/java/org/fastcampus/oruryclient/config/ControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/service/ReviewReactionServiceTest.java
  orury-common/src/main/java/org/fastcampus/orurycommon/error/code/ReviewReactionErrorCode.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/review/db/model/ReviewReaction.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/review/db/model/ReviewReactionPK.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/review/db/repository/ReviewReactionRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/review/db/repository/ReviewRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/review/dto/ReviewReactionDto.java
  orury-domain/src/main/resources/db/migration/V1.0.10__modify_review_fk.sql
  orury-domain/src/main/resources/db/migration/V1.0.9__create_review_reaction.sql
Labels: 🛢 DB, 💻 BE, ✨ Feature, ✅ Test, 🔨 Refactor

#149 Feat : 카카오 OAuth2.0 로그인 구현
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/controller/AuthController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/converter/message/AuthMessage.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/converter/response/LoginResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/jwt/JwtTokenFilter.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/jwt/JwtTokenProvider.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/oauth/OAuth2Attribute.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/oauth/OAuth2UserService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/oauth/OAuthSuccessHandler.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/oauth/SocialProviderType.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/service/AuthService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/global/config/SecurityConfig.java
  orury-client/src/main/resources/application.yaml
  orury-domain/src/main/java/org/fastcampus/orurydomain/user/db/repository/UserRepository.java
Labels: 💻 BE, ✨ Feature

#148 Refactor : PostServiceTest 커버리지 강화
  orury-client/src/test/java/org/fastcampus/oruryclient/comment/service/CommentLikeServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/comment/service/CommentServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/post/controller/PostControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/post/service/PostLikeServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/post/service/PostServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/service/ReviewServiceTest.java
Labels: 💻 BE, ✅ Test, 🔨 Refactor

#156 Feat & Refactor: RefreshToken 관리 프로세스 구현 & JwtToken 관련 Refactoring
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/controller/AuthController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/converter/response/LoginResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/jwt/JwtTokenFilter.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/jwt/JwtTokenProvider.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/oauth/OAuthSuccessHandler.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/auth/db/model/RefreshToken.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/auth/db/repository/RefreshTokenRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/auth/dto/JwtToken.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/user/db/model/UserEnums.java
  orury-domain/src/main/resources/db/migration/V1.0.11__create_refresh_token_table.sql
Labels: 💻 BE, ✨ Feature, 🔨 Refactor

#158 Refactor: @AuthenticationPrincipal 적용
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/controller/CommentController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/controller/CommentLikeController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/controller/PostController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/controller/PostLikeController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/controller/ReviewController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/controller/ReviewReactionController.java
  orury-client/src/test/java/org/fastcampus/oruryclient/comment/controller/CommentControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/comment/controller/CommentLikeControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/config/WithUserPrincipal.java
  orury-client/src/test/java/org/fastcampus/oruryclient/config/WithUserPrincipalSecurityContextFactory.java
  orury-client/src/test/java/org/fastcampus/oruryclient/post/controller/PostControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/post/controller/PostLikeControllerTest.java
Labels: 💻 BE, ✅ Test, 🔨 Refactor

#162 Refactor : 서버 암호화 추가 및 cors 허용 도메인 추가
  orury-client/src/main/java/org/fastcampus/oruryclient/global/config/SecurityConfig.java
  orury-client/src/main/resources/application.yaml
Labels: ⚙️Settings, 💻 BE

#164 refactor : gym 테이블 수정
  orury-domain/src/main/resources/db/migration/V1.0.12__modify_gym_data.sql
Labels: 🛢 DB, 🔨 Refactor

#159 Settings : logback 설정
  orury-admin/src/main/resources/application.yaml
  orury-batch/src/main/resources/application.yml
  orury-batch/src/main/resources/logback.xml
  orury-client/src/main/resources/application.yml
  orury-client/src/main/resources/logback.xml
  orury-common/src/main/resources/application.yml
  orury-domain/src/main/resources/application.yml
Labels: ⚙️Settings, 💻 BE

#169 Feat : DB replication 및 라우팅
  orury-client/src/main/java/org/fastcampus/oruryclient/global/config/DataSourceConfig.java
  orury-client/src/main/java/org/fastcampus/oruryclient/global/config/DataSourceRouter.java
  orury-client/src/main/resources/application.yml
Labels: Chore, 🛢 DB, 🧱Infra

#167 fix : batch 키 수정
  orury-batch/src/main/resources/application.yml
Labels: 🐞 Fix, 💻 BE

#168 Feat: 암장 조회 API 구현
  orury-batch/src/main/java/org/fastcampus/orurybatch/dto/GymResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/global/constants/NumberConstants.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/controller/GymController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/controller/GymLikeController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/converter/message/GymMessage.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/converter/request/GymSearchRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/converter/response/GymDetailResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/converter/response/GymDetailStatistics.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/converter/response/GymsResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/service/GymLikeService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/service/GymService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/service/ReviewService.java
  orury-client/src/test/java/org/fastcampus/oruryclient/gym/controller/GymControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/gym/controller/GymLikeControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/gym/service/GymLikeServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/gym/service/GymServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/controller/ReviewControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/service/ReviewReactionServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/service/ReviewServiceTest.java
  orury-common/src/main/java/org/fastcampus/orurycommon/util/BusinessHoursConverter.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/gym/db/model/Gym.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/gym/db/model/GymLike.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/gym/db/model/GymLikePK.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/gym/db/repository/GymLikeRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/gym/db/repository/GymRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/gym/dto/GymDto.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/gym/dto/GymLikeDto.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/review/db/repository/ReviewRepository.java
  orury-domain/src/main/resources/db/migration/V1.0.13__add_reviewCount_column_to_gym.sql
  orury-domain/src/main/resources/db/migration/V1.0.14__create_gymLike_table.sql
Labels: 💻 BE, ✨ Feature

#175 Feat : ReviewReaction controller testcode
  orury-client/src/main/java/org/fastcampus/oruryclient/review/controller/ReviewReactionController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/service/ReviewReactionService.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/controller/ReviewReactionControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/service/ReviewReactionServiceTest.java
Labels: 💻 BE, ✅ Test, 🔨 Refactor

#179 Test: 암장 도메인 Service 테스트코드 작성
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/controller/GymLikeController.java
  orury-client/src/main/resources/application.yml
  orury-client/src/test/java/org/fastcampus/oruryclient/gym/service/GymLikeServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/gym/service/GymServiceTest.java
Labels: 💻 BE, ✅ Test

#172 Refactor : S3이미지 저장, 사진 생성 수정이 필요한 기능에 MultipartFile 추가
  orury-client/src/main/java/org/fastcampus/oruryclient/ImageController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/controller/AuthController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/controller/CommentController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/controller/CommentLikeController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/converter/response/GymDetailResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/converter/response/GymsResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/controller/PostController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/controller/PostLikeController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/converter/response/PostResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/service/PostService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/controller/ReviewController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/controller/ReviewReactionController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/request/ReviewCreateRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/request/ReviewUpdateRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/response/ReviewResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/response/ReviewsResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/service/ReviewService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/controller/UserController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/request/ProfileImageRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/service/UserService.java
  orury-client/src/main/resources/application.yml
  orury-client/src/test/java/org/fastcampus/oruryclient/comment/controller/CommentControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/comment/controller/CommentLikeControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/config/ControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/post/controller/PostControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/post/controller/PostLikeControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/post/service/PostServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/controller/ReviewControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/controller/ReviewReactionControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/service/ReviewReactionServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/service/ReviewServiceTest.java
  orury-common/src/main/java/org/fastcampus/orurycommon/util/ImageUrlConverter.java
  orury-common/src/main/java/org/fastcampus/orurycommon/util/S3Folder.java
  orury-common/src/main/java/org/fastcampus/orurycommon/util/S3Repository.java
  orury-common/src/main/java/org/fastcampus/orurycommon/util/S3Service.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/post/dto/PostDto.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/review/dto/ReviewDto.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/user/dto/UserDto.java
Labels: 💻 BE, 🔨 Refactor

#181 Refactor : 이미지 관련 테스트 API작성 및 Request MultipartFile 폼 변경
  orury-client/src/main/java/org/fastcampus/oruryclient/post/controller/PostController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/converter/request/PostUpdateRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/controller/ReviewController.java
  orury-client/src/main/resources/application.yml
  orury-client/src/test/java/org/fastcampus/oruryclient/post/controller/PostControllerTest.java
  orury-common/src/main/java/org/fastcampus/orurycommon/util/S3Repository.java
Labels: 💻 BE, ✨ Feature, 🔨 Refactor

#185 Fix : swagger docs 접근 허용
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/jwt/JwtTokenFilter.java
  orury-common/src/main/java/org/fastcampus/orurycommon/log/LoggerFilter.java
Labels: 🐞 Fix, 💻 BE

#186 Settings : Github Actions를 활용한 자동 배포 설정
  .github/workflows/bepo.yml
  .github/workflows/gradle.yml
  appspec.yml
  orury-client/src/main/resources/application.yml
  orury-common/src/main/java/org/fastcampus/orurycommon/config/JasyptConfig.java
  scripts/deploy.sh
  scripts/health_check.sh
  scripts/run_new_was.sh
  scripts/switch.sh
Labels: ⚙️Settings

#183 Refactor : 소셜로그인 리팩토링 작업
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/controller/AuthController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/converter/message/AuthMessage.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/converter/request/LoginRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/converter/response/LoginResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/jwt/JwtTokenFilter.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/service/AuthService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/strategy/AppleLoginStrategy.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/strategy/KakaoLoginStrategy.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/strategy/LoginStrategy.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/strategy/LoginStrategyManager.java
  orury-client/src/main/java/org/fastcampus/oruryclient/global/config/SecurityConfig.java
  orury-client/src/main/resources/application.yml
  orury-client/src/test/java/org/fastcampus/oruryclient/config/ControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/post/controller/PostControllerTest.java
  orury-common/src/main/java/org/fastcampus/orurycommon/error/code/AuthErrorCode.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/auth/dto/LoginDto.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/auth/dto/kakao/KakaoAccount.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/auth/dto/kakao/KakaoAccountDto.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/auth/dto/kakao/KakaoTokenDto.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/auth/dto/kakao/Profile.java
Labels: 💻 BE, 📬 API, 🔨 Refactor

#189 Refactor : gym의 total_score, review_count 필드 추가에 따른 review 리팩토링
  orury-batch/src/main/java/org/fastcampus/orurybatch/dto/GymResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/converter/response/GymDetailResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/converter/response/GymsResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/controller/ReviewController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/service/ReviewService.java
  orury-client/src/test/java/org/fastcampus/oruryclient/gym/service/GymServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/controller/ReviewControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/service/ReviewReactionServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/service/ReviewServiceTest.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/gym/db/model/Gym.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/gym/db/repository/GymRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/gym/dto/GymDto.java
  orury-domain/src/main/resources/db/migration/V1.0.15__delete_gym_score_average.sql
  orury-domain/src/main/resources/db/migration/V1.0.16__create_gym_totalscore_and_reviewcount.sql
Labels: ✅ Test, 🔨 Refactor

#192 Test : Gym/Post Controller 테스트코드
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/controller/GymController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/converter/request/GymSearchRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/converter/response/GymDetailStatistics.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/converter/response/GymResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/converter/response/GymReviewStatistics.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/converter/response/GymsResponse.java
  orury-client/src/test/java/org/fastcampus/oruryclient/config/ControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/gym/controller/GymControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/gym/controller/GymLikeControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/gym/service/GymLikeServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/gym/service/GymServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/post/controller/PostControllerTest.java
Labels: 💻 BE, ✅ Test, 🔨 Refactor

#197 Test : JwtTokenFilter & JwtTokenProvider 테스트코드
  orury-client/src/test/java/org/fastcampus/oruryclient/auth/jwt/JwtTokenFilterTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/auth/jwt/JwtTokenProviderTest.java
Labels: 💻 BE, ✅ Test

#205 Settings : Docker-Compose를 활용한 환경 구축
  .github/workflows/bepo.yml
  build.gradle
  docker-compose.yml
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/jwt/JwtTokenFilter.java
  orury-client/src/main/java/org/fastcampus/oruryclient/global/config/SecurityConfig.java
  orury-client/src/main/resources/application.yml
  orury-common/src/main/java/org/fastcampus/orurycommon/log/LoggerFilter.java
  prometheus.yml
  scripts/deploy.sh
Labels: ⚙️Settings

#204 Refactor : ReviewReaction(리뷰 반응) API 하나로 통합
  orury-client/src/main/java/org/fastcampus/oruryclient/review/controller/ReviewReactionController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/message/ReviewMessage.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/service/ReviewReactionService.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/controller/ReviewReactionControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/service/ReviewReactionServiceTest.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/review/db/repository/ReviewRepository.java
Labels: 💻 BE, ✅ Test, 🔨 Refactor

#202 Feat : 마이페이지 내가 쓴 리뷰, 게시글, 댓글 조회 기능 구현 및 WithCursorResponse 리팩토링
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/service/CommentService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/global/IdIdentifiable.java
  orury-client/src/main/java/org/fastcampus/oruryclient/global/WithCursorResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/service/PostService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/service/ReviewService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/controller/UserController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/message/UserMessage.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/request/UserInfoRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/response/MyCommentResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/response/MyPostResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/response/MyReviewResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/response/MypageResponse.java
  orury-client/src/test/java/org/fastcampus/oruryclient/comment/service/CommentServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/post/service/PostServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/service/ReviewServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/user/db/controller/UserControllerTest.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/comment/db/repository/CommentRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/post/db/repository/PostRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/review/db/repository/ReviewRepository.java
Labels: 💻 BE, ✨ Feature, ✅ Test, 🔨 Refactor

#209 Refactor : 작업환경 (dev, prod)에 따른 application.yml 분리
  orury-client/src/main/java/org/fastcampus/oruryclient/global/config/DataSourceConfig.java
  orury-client/src/main/resources/application-dev.yml
  orury-client/src/main/resources/application-prod.yml
  orury-client/src/main/resources/application.yml
Labels: ⚙️Settings, 🔨 Refactor

#213 Fix : 이미지 관련 로직 점검
  .github/workflows/bepo.yml
  orury-common/src/main/java/org/fastcampus/orurycommon/util/ImageUrlConverter.java
Labels: ❗ Bug, 💻 BE

#218 Refactor : 로그인 및 회원가입 로직 수정
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/controller/AuthController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/converter/response/LoginResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/converter/response/SignUpResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/jwt/JwtTokenFilter.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/jwt/JwtTokenProvider.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/service/AuthService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/strategy/KakaoLoginStrategy.java
  orury-client/src/test/java/org/fastcampus/oruryclient/auth/jwt/JwtTokenFilterTest.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/auth/dto/LoginDto.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/auth/dto/SignUpDto.java
Labels: 💻 BE, 📬 API, 🔨 Refactor

#219 develop to stage merge
  .github/workflows/bepo.yml
  build.gradle
  docker-compose.yml
  orury-batch/src/main/java/org/fastcampus/orurybatch/OruryBatchApplication.java
  orury-batch/src/main/java/org/fastcampus/orurybatch/job/GymJobScheduler.java
  orury-batch/src/main/resources/application.yml
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/controller/AuthController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/converter/response/LoginResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/converter/response/SignUpResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/jwt/JwtTokenFilter.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/jwt/JwtTokenProvider.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/service/AuthService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/strategy/KakaoLoginStrategy.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/service/CommentService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/global/IdIdentifiable.java
  orury-client/src/main/java/org/fastcampus/oruryclient/global/WithCursorResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/global/config/DataSourceConfig.java
  orury-client/src/main/java/org/fastcampus/oruryclient/global/config/SecurityConfig.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/service/PostService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/controller/ReviewReactionController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/message/ReviewMessage.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/service/ReviewReactionService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/service/ReviewService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/controller/UserController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/message/UserMessage.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/request/UserInfoRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/response/MyCommentResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/response/MyPostResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/response/MyReviewResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/response/MypageResponse.java
  orury-client/src/main/resources/application-dev.yml
  orury-client/src/main/resources/application-prod.yml
  orury-client/src/main/resources/application.yml
  orury-client/src/test/java/org/fastcampus/oruryclient/auth/jwt/JwtTokenFilterTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/comment/service/CommentServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/post/service/PostServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/controller/ReviewReactionControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/service/ReviewReactionServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/service/ReviewServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/user/db/controller/UserControllerTest.java
  orury-common/src/main/java/org/fastcampus/orurycommon/log/LoggerFilter.java
  orury-common/src/main/java/org/fastcampus/orurycommon/util/ImageUrlConverter.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/auth/dto/LoginDto.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/auth/dto/SignUpDto.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/comment/db/repository/CommentRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/post/db/repository/PostRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/review/db/repository/ReviewRepository.java
  prometheus.yml
  scripts/deploy.sh
Labels: 🌏 Deploy, 💻 BE

#220 Deploy : stage to main merge
  .github/workflows/bepo.yml
  build.gradle
  docker-compose.yml
  orury-batch/src/main/java/org/fastcampus/orurybatch/OruryBatchApplication.java
  orury-batch/src/main/java/org/fastcampus/orurybatch/job/GymJobScheduler.java
  orury-batch/src/main/resources/application.yml
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/controller/AuthController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/converter/response/LoginResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/converter/response/SignUpResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/jwt/JwtTokenFilter.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/jwt/JwtTokenProvider.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/service/AuthService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/strategy/KakaoLoginStrategy.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/service/CommentService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/global/IdIdentifiable.java
  orury-client/src/main/java/org/fastcampus/oruryclient/global/WithCursorResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/global/config/DataSourceConfig.java
  orury-client/src/main/java/org/fastcampus/oruryclient/global/config/SecurityConfig.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/service/PostService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/controller/ReviewReactionController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/message/ReviewMessage.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/service/ReviewReactionService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/service/ReviewService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/controller/UserController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/message/UserMessage.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/request/UserInfoRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/response/MyCommentResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/response/MyPostResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/response/MyReviewResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/response/MypageResponse.java
  orury-client/src/main/resources/application-dev.yml
  orury-client/src/main/resources/application-prod.yml
  orury-client/src/main/resources/application.yml
  orury-client/src/test/java/org/fastcampus/oruryclient/auth/jwt/JwtTokenFilterTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/comment/service/CommentServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/post/service/PostServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/controller/ReviewReactionControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/service/ReviewReactionServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/service/ReviewServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/user/db/controller/UserControllerTest.java
  orury-common/src/main/java/org/fastcampus/orurycommon/log/LoggerFilter.java
  orury-common/src/main/java/org/fastcampus/orurycommon/util/ImageUrlConverter.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/auth/dto/LoginDto.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/auth/dto/SignUpDto.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/comment/db/repository/CommentRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/post/db/repository/PostRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/review/db/repository/ReviewRepository.java
  prometheus.yml
  scripts/deploy.sh
Labels: 🌏 Deploy, 💻 BE

#217 Refactor : Logging 리팩토링
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/jwt/JwtTokenFilter.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/jwt/JwtTokenProvider.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/service/CommentService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/service/PostService.java
  orury-common/src/main/java/org/fastcampus/orurycommon/error/exception/GlobalExceptionHandler.java
  orury-common/src/main/java/org/fastcampus/orurycommon/log/LogAspect.java
  orury-common/src/main/java/org/fastcampus/orurycommon/log/LoggerFilter.java
  orury-common/src/main/java/org/fastcampus/orurycommon/log/Logging.java
Labels: 💻 BE, 🔨 Refactor

#223 Test : Repository Layer Test Setting
  build.gradle
  orury-client/src/main/resources/application.yml
  orury-client/src/test/java/org/fastcampus/oruryclient/user/db/repository/UserRepositoryTest.java
  orury-domain/build.gradle
  orury-domain/src/main/java/org/fastcampus/orurydomain/OruryDomainApplication.java
  orury-domain/src/test/java/org/fastcampus/orurydomain/config/RepositoryTest.java
  orury-domain/src/test/java/org/fastcampus/orurydomain/config/TestJpaConfig.java
  orury-domain/src/test/java/org/fastcampus/orurydomain/notice/db/repository/NoticeRepositoryTest.java
  orury-domain/src/test/resources/application-test.yml
Labels: 💻 BE, ✅ Test

#224 Chore : 메세지 한글화 작업
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/converter/message/CommentMessage.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/converter/message/GymMessage.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/converter/message/PostMessage.java
Labels: 🎸Chore, 💻 BE
