Repository Kernel360/f1-Orury-Backend, pull requests merged in 2024-02, with the labels that each got.

#230 Refactor : GET 요청 requestbody -> requestparam
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/controller/GymController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/converter/request/GymSearchRequest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/gym/controller/GymControllerTest.java
Labels: 💻 BE, 📬 API, 🔨 Refactor

#232 Fix : save() -> saveAndFlush()로 변경
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/service/AuthService.java
Labels: 🐞 Fix, 💻 BE, 📬 API

#233 Refactor : 비회원 로그인 시 email값 미전달 처리
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/converter/response/LoginResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/strategy/KakaoLoginStrategy.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/auth/dto/LoginDto.java
Labels: 💻 BE, 📬 API, 🔨 Refactor

#234 Feat : 유저 탈퇴 구현
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/converter/request/SignUpRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/jwt/JwtTokenProvider.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/oauth/OAuth2UserService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/controller/CommentController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/converter/request/CommentCreateRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/converter/response/CommentResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/converter/response/CommentsWithCursorResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/service/CommentService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/global/WithCursorResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/converter/response/GymResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/controller/PostController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/converter/response/PostsWithCursorResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/service/PostService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/controller/ReviewController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/response/ReviewsResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/response/ReviewsWithCursorResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/service/ReviewReactionService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/service/ReviewService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/controller/UserController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/request/ProfileImageRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/request/UserInfoRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/response/MyReviewResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/service/UserService.java
  orury-client/src/test/java/org/fastcampus/oruryclient/auth/jwt/JwtTokenProviderTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/comment/controller/CommentControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/comment/service/CommentLikeServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/comment/service/CommentServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/config/WithUserPrincipalSecurityContextFactory.java
  orury-client/src/test/java/org/fastcampus/oruryclient/gym/controller/GymControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/post/controller/PostControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/post/service/PostLikeServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/post/service/PostServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/controller/ReviewControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/service/ReviewReactionServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/service/ReviewServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/user/db/controller/UserControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/user/db/model/UserTest.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/auth/dto/LoginDto.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/comment/db/repository/CommentLikeRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/global/constants/Constants.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/global/constants/NumberConstants.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/gym/db/repository/GymLikeRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/post/db/repository/PostLikeRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/post/db/repository/PostRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/review/db/repository/ReviewReactionRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/user/db/model/User.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/user/dto/UserDto.java
  orury-domain/src/main/resources/db/migration/V1.0.17__delete_userWithdrawal_table.sql
  orury-domain/src/main/resources/db/migration/V1.0.18__add_isDeleted_column_to_user_table.sql
  orury-domain/src/main/resources/db/migration/V1.0.19__add_cascade_delete_to_postLike&comment&commentLike.sql
Labels: 🛢 DB, 💻 BE, ✨ Feature, 🔨 Refactor

#238 Refactor : 게시글 좋아요 Service 선언부, 구현부로 분리
  orury-client/src/main/java/org/fastcampus/oruryclient/post/service/PostLikeService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/service/PostLikeServiceImpl.java
  orury-client/src/test/java/org/fastcampus/oruryclient/post/service/PostLikeServiceTest.java
Labels: 💻 BE, 🔨 Refactor

#237 Bugfix & Refactor : Response관련 자잘한 버그 수정 & 토큰 재발급 requestBody 변경
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/controller/AuthController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/converter/request/RefreshTokenRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/converter/response/GymResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/converter/response/GymsResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/converter/response/PostResponse.java
Labels: 🐞 Fix, 💻 BE, 🔨 Refactor

#243 Refactor : 불필요한 의존성 제거
  build.gradle
  orury-admin/build.gradle
  orury-batch/build.gradle
  orury-client/build.gradle
  orury-common/build.gradle
  orury-common/src/main/java/org/fastcampus/orurycommon/config/SwaggerConfig.java
  orury-domain/build.gradle
Labels: 💻 BE, 🔨 Refactor

#245 Fix : 프로필 닉네임 수정시 URL 그대로 저장되는 오류 수정
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/request/UserInfoRequest.java
Labels: ❗ Bug, 💻 BE

#247 Settings : 500에러시 빠르게 대응 가능한 슬랙 알림 구현
  orury-client/src/main/resources/application.yml
  orury-client/src/test/java/org/fastcampus/oruryclient/config/ControllerTest.java
  orury-common/build.gradle
  orury-common/src/main/java/org/fastcampus/orurycommon/config/SlackMessage.java
  orury-common/src/main/java/org/fastcampus/orurycommon/error/code/LogTemplate.java
  orury-common/src/main/java/org/fastcampus/orurycommon/log/LoggerFilter.java
Labels: ⚙️Settings, 💻 BE

#253 Settings/#252 sql p6spy
  orury-client/src/main/resources/application.yml
  orury-common/build.gradle
  orury-common/src/main/java/org/fastcampus/orurycommon/config/P6SpyFormatter.java
  orury-common/src/main/resources/application.yml
  orury-domain/src/main/resources/application.yml
Labels: ⚙️Settings, 💻 BE

#259 Chore : 마이페이지 조회 시 user_id 반환
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/response/MypageResponse.java
  orury-client/src/test/java/org/fastcampus/oruryclient/user/controller/UserControllerTest.java
Labels: 🎸Chore

#257 Fix : 게시글 관련 이슈 수정
  orury-client/src/main/resources/application.yml
  orury-common/src/main/java/org/fastcampus/orurycommon/config/FlywayConfig.java
Labels: 🐞 Fix, 💻 BE, 📬 API

#256 Refactor : 리뷰 api 통합테스트 및 리팩토링
  orury-client/src/main/java/org/fastcampus/oruryclient/review/controller/ReviewController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/request/ReviewUpdateRequest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/controller/ReviewControllerTest.java
Labels: 💻 BE, ✅ Test, 🔨 Refactor

#261 Feat : 애플 OAuth 인증 구현 (w/ Feign)
  orury-client/build.gradle
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/oauth/OAuth2Attribute.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/oauth/OAuth2UserService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/oauth/OAuthSuccessHandler.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/oauth/SocialProviderType.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/strategy/AppleLoginStrategy.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/strategy/applefeign/AppleAuthClient.java
  orury-client/src/main/java/org/fastcampus/oruryclient/global/config/FeignConfig.java
  orury-client/src/main/java/org/fastcampus/oruryclient/global/config/SecurityConfig.java
  orury-client/src/main/resources/application.yml
  orury-common/src/main/java/org/fastcampus/orurycommon/util/TokenDecoder.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/auth/dto/apple/AppleIdTokenPayload.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/auth/dto/apple/AppleOAuthTokenDto.java
Labels: 💻 BE, ✨ Feature

#263 Refactor : Image URL 변환 Refactoring
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/service/CommentService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/converter/response/GymResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/converter/response/GymsResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/service/GymService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/controller/PostController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/converter/request/PostCreateRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/converter/request/PostUpdateRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/converter/response/PostResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/converter/response/PostsResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/service/PostService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/controller/ReviewController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/request/ReviewCreateRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/response/ReviewResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/response/ReviewsResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/service/ReviewService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/response/MyPostResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/response/MyReviewResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/service/UserService.java
  orury-client/src/main/resources/application.yml
  orury-client/src/test/java/org/fastcampus/oruryclient/comment/controller/CommentControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/comment/service/CommentLikeServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/comment/service/CommentServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/gym/controller/GymControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/gym/service/GymServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/post/controller/PostControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/post/service/PostLikeServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/post/service/PostServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/controller/ReviewControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/service/ReviewReactionServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/service/ReviewServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/user/controller/UserControllerTest.java
  orury-common/src/main/java/org/fastcampus/orurycommon/util/ImageUtils.java
  orury-common/src/main/java/org/fastcampus/orurycommon/util/S3Folder.java
  orury-common/src/main/java/org/fastcampus/orurycommon/util/S3Repository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/global/listener/EntityImageConverter.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/gym/db/model/Gym.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/gym/dto/GymDto.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/post/db/model/Post.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/post/dto/PostDto.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/review/db/model/Review.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/review/dto/ReviewDto.java
Labels: 💻 BE, 🔨 Refactor

#268 Feat : 게시글 작성자의 id 추가
  orury-client/src/main/java/org/fastcampus/oruryclient/post/converter/response/PostResponse.java
  orury-client/src/main/resources/application.yml
Labels: 💻 BE, 📬 API, ✨ Feature

#270 Refactor : gym 테이블의 deafult값 추가
  orury-domain/src/main/resources/db/migration/V1.0.20__modify_default_values.sql
Labels: 🛢 DB, 💻 BE, 🔨 Refactor

#274 Fix : 암장 리뷰 평균점수 소수점 첫째 자리까지 반올림
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/converter/response/CommentResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/converter/response/GymResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/converter/response/GymsResponse.java
Labels: 🐞 Fix, 💻 BE

#277 Test : UserController / UserService 테스트코드 작성
  orury-client/src/test/java/org/fastcampus/oruryclient/review/service/ReviewServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/user/controller/UserControllerTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/user/service/UserServiceTest.java
Labels: 💻 BE, ✅ Test

#283 Refactor : Json snake_case 변환 전역적 관리 & SpringDataJpa 불필요한 언더바 제거
  orury-batch/src/main/java/org/fastcampus/orurybatch/dto/KakaoMapGymResponse.java
  orury-batch/src/main/resources/application.yml
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/converter/request/LoginRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/converter/request/RefreshTokenRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/converter/request/SignUpRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/converter/response/LoginResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/converter/response/SignUpResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/converter/request/CommentCreateRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/converter/request/CommentUpdateRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/converter/response/CommentResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/converter/response/CommentsWithCursorResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/service/CommentService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/converter/response/GymResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/converter/response/GymReviewStatistics.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/converter/response/GymsResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/converter/request/PostCreateRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/converter/request/PostUpdateRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/converter/response/PostResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/converter/response/PostsResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/converter/response/PostsWithCursorResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/converter/response/PostsWithPageResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/request/ReviewCreateRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/request/ReviewReactionRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/request/ReviewUpdateRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/response/ReviewResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/response/ReviewsResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/response/ReviewsWithCursorResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/service/ReviewService.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/request/ProfileImageRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/request/UserInfoRequest.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/response/MyCommentResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/response/MyPostResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/response/MyReviewResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/response/MypageResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/service/UserService.java
  orury-client/src/main/resources/application.yml
  orury-client/src/test/java/org/fastcampus/oruryclient/comment/service/CommentServiceTest.java
  orury-client/src/test/java/org/fastcampus/oruryclient/review/service/ReviewServiceTest.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/auth/dto/JwtToken.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/auth/dto/kakao/KakaoAccount.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/auth/dto/kakao/KakaoAccountDto.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/auth/dto/kakao/KakaoOAuthTokenDto.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/auth/dto/kakao/Profile.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/comment/db/repository/CommentRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/post/db/repository/PostLikeRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/post/db/repository/PostRepository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/review/db/repository/ReviewRepository.java
Labels: 💻 BE, 🔨 Refactor

#285 Refactor : 미사용 클래스 삭제 , 코드 명시적 작성
  orury-client/src/main/java/org/fastcampus/oruryclient/review/service/ReviewReactionService.java
  orury-client/src/test/java/org/fastcampus/oruryclient/user/service/UserServiceTest.java
  orury-common/src/main/java/org/fastcampus/orurycommon/util/ImageUrlConverter.java
Labels: 💻 BE, 🔨 Refactor

#290 Refactor : 배치 모듈 불필요 코드 제거
  .github/workflows/bepo.yml
  orury-batch/src/main/java/org/fastcampus/orurybatch/client/KakaoMapClient.java
  orury-batch/src/main/java/org/fastcampus/orurybatch/config/JobCompletionNotificationListener.java
  orury-batch/src/main/java/org/fastcampus/orurybatch/job/GymItemProcessor.java
  orury-batch/src/main/java/org/fastcampus/orurybatch/job/GymItemReader.java
  orury-batch/src/main/java/org/fastcampus/orurybatch/job/GymJobConfiguration.java
  orury-batch/src/main/java/org/fastcampus/orurybatch/util/Constant.java
  orury-batch/src/main/java/org/fastcampus/orurybatch/util/SqlQuery.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/controller/AuthController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/auth/converter/response/LoginResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/controller/CommentController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/controller/CommentLikeController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/comment/converter/response/CommentResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/global/config/WebConfig.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/controller/GymController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/gym/controller/GymLikeController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/controller/PostController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/controller/PostLikeController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/converter/response/PostResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/post/converter/response/PostsResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/controller/ReviewController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/controller/ReviewReactionController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/review/converter/response/ReviewsResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/controller/UserController.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/response/MyCommentResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/response/MyPostResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/response/MyReviewResponse.java
  orury-client/src/main/java/org/fastcampus/oruryclient/user/converter/response/MypageResponse.java
  orury-client/src/main/resources/application-dev.yml
  orury-client/src/main/resources/application-prod.yml
  orury-client/src/main/resources/application.yml
  orury-client/src/test/java/org/fastcampus/oruryclient/post/controller/PostControllerTest.java
  orury-common/src/main/java/org/fastcampus/orurycommon/util/ImageUtils.java
  orury-common/src/main/java/org/fastcampus/orurycommon/util/S3Repository.java
  orury-domain/src/main/java/org/fastcampus/orurydomain/base/converter/ApiResponse.java
  scripts/deploy.sh
Labels: 💻 BE, 🔨 Refactor

#296 Refactor : 회원가입용 토큰 만료 시, 다른 에러 메세지 반환
  orury-client/src/main/java/org/orury/client/auth/jwt/JwtTokenProvider.java
  orury-client/src/test/java/org/orury/client/auth/jwt/JwtTokenProviderTest.java
  orury-common/src/main/java/org/orury/common/error/code/TokenErrorCode.java
  orury-domain/src/main/java/org/orury/domain/auth/db/repository/RefreshTokenRepository.java
Labels: 💻 BE, 🔨 Refactor

#299 Fix : 리프레쉬 토큰 발급 로직 수정
  orury-client/src/main/java/org/orury/client/auth/controller/AuthController.java
  orury-client/src/main/java/org/orury/client/auth/converter/request/RefreshTokenRequest.java
  orury-client/src/main/java/org/orury/client/auth/jwt/JwtTokenProvider.java
  orury-client/src/test/java/org/orury/client/auth/jwt/JwtTokenProviderTest.java
Labels: 💻 BE, ✅ Test

#293 Refactor : User,Comment 삭제 리팩토링
  orury-client/src/main/java/org/orury/client/comment/service/CommentService.java
  orury-client/src/main/java/org/orury/client/user/service/UserService.java
  orury-client/src/test/java/org/orury/client/comment/service/CommentServiceTest.java
  orury-domain/build.gradle
  orury-domain/src/main/java/org/orury/domain/OruryDomainApplication.java
  orury-domain/src/main/java/org/orury/domain/comment/db/model/Comment.java
  orury-domain/src/main/java/org/orury/domain/comment/db/repository/CommentRepository.java
  orury-domain/src/main/java/org/orury/domain/global/constants/Constants.java
  orury-domain/src/main/java/org/orury/domain/user/db/model/User.java
  orury-domain/src/test/resources/application-test.yml
Labels: 💻 BE, 🔨 Refactor

#315 Feat : Reader, Store의 CustomException 추가
  orury-common/src/main/java/org/orury/common/error/exception/GlobalExceptionHandler.java
  orury-common/src/main/java/org/orury/common/error/exception/InfraImplException.java
Labels: 💻 BE, ✨ Feature

#318 Refactor : Review 리팩토링 with DDD, DIP
  orury-client/src/main/java/org/orury/client/gym/application/GymFacade.java
  orury-client/src/main/java/org/orury/client/gym/interfaces/response/GymReviewStatistics.java
  orury-client/src/main/java/org/orury/client/post/application/PostFacade.java
  orury-client/src/main/java/org/orury/client/post/interfaces/PostController.java
  orury-client/src/main/java/org/orury/client/review/application/ReviewFacade.java
  orury-client/src/main/java/org/orury/client/review/application/ReviewService.java
  orury-client/src/main/java/org/orury/client/review/application/ReviewServiceImpl.java
  orury-client/src/main/java/org/orury/client/review/controller/ReviewController.java
  orury-client/src/main/java/org/orury/client/review/controller/ReviewReactionController.java
  orury-client/src/main/java/org/orury/client/review/interfaces/ReviewController.java
  orury-client/src/main/java/org/orury/client/review/interfaces/message/ReviewMessage.java
  orury-client/src/main/java/org/orury/client/review/interfaces/request/ReviewCreateRequest.java
  orury-client/src/main/java/org/orury/client/review/interfaces/request/ReviewReactionRequest.java
  orury-client/src/main/java/org/orury/client/review/interfaces/request/ReviewUpdateRequest.java
  orury-client/src/main/java/org/orury/client/review/interfaces/response/ReviewsResponse.java
  orury-client/src/main/java/org/orury/client/review/interfaces/response/ReviewsWithCursorResponse.java
  orury-client/src/main/java/org/orury/client/review/service/ReviewReactionService.java
  orury-client/src/main/java/org/orury/client/review/service/ReviewService.java
  orury-client/src/main/java/org/orury/client/user/application/UserFacade.java
  orury-client/src/main/java/org/orury/client/user/interfaces/UserController.java
  orury-client/src/main/java/org/orury/client/user/interfaces/response/MyReviewResponse.java
  orury-client/src/test/java/org/orury/client/config/ControllerTest.java
  orury-client/src/test/java/org/orury/client/review/service/ReviewReactionServiceTest.java
  orury-domain/src/main/java/org/orury/domain/review/domain/ReviewReader.java
  orury-domain/src/main/java/org/orury/domain/review/domain/ReviewStore.java
  orury-domain/src/main/java/org/orury/domain/review/domain/dto/ReviewDto.java
  orury-domain/src/main/java/org/orury/domain/review/domain/dto/ReviewReactionDto.java
  orury-domain/src/main/java/org/orury/domain/review/domain/entity/Review.java
  orury-domain/src/main/java/org/orury/domain/review/domain/entity/ReviewReaction.java
  orury-domain/src/main/java/org/orury/domain/review/domain/entity/ReviewReactionPK.java
  orury-domain/src/main/java/org/orury/domain/review/domain/infrastructure/ReviewReactionRepository.java
  orury-domain/src/main/java/org/orury/domain/review/domain/infrastructure/ReviewReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/review/domain/infrastructure/ReviewRepository.java
  orury-domain/src/main/java/org/orury/domain/review/domain/infrastructure/ReviewStoreImpl.java
  orury-domain/src/main/java/org/orury/domain/user/domain/UserServiceImpl.java
  orury-domain/src/test/java/org/orury/domain/config/TestRepositoryUtils.java
Labels: 💻 BE, 📬 API, 🔨 Refactor

#308 Refactor : Comment(댓글) 리팩토링 with DDD, DIP
  orury-client/src/main/java/org/orury/client/comment/application/CommentFacade.java
  orury-client/src/main/java/org/orury/client/comment/application/CommentService.java
  orury-client/src/main/java/org/orury/client/comment/application/CommentServiceImpl.java
  orury-client/src/main/java/org/orury/client/comment/controller/CommentController.java
  orury-client/src/main/java/org/orury/client/comment/controller/CommentLikeController.java
  orury-client/src/main/java/org/orury/client/comment/interfaces/CommentController.java
  orury-client/src/main/java/org/orury/client/comment/interfaces/message/CommentMessage.java
  orury-client/src/main/java/org/orury/client/comment/interfaces/request/CommentCreateRequest.java
  orury-client/src/main/java/org/orury/client/comment/interfaces/request/CommentUpdateRequest.java
  orury-client/src/main/java/org/orury/client/comment/interfaces/response/CommentResponse.java
  orury-client/src/main/java/org/orury/client/comment/interfaces/response/CommentsWithCursorResponse.java
  orury-client/src/main/java/org/orury/client/comment/service/CommentLikeService.java
  orury-client/src/main/java/org/orury/client/comment/service/CommentService.java
  orury-client/src/main/java/org/orury/client/gym/application/GymFacade.java
  orury-client/src/main/java/org/orury/client/gym/application/GymService.java
  orury-client/src/main/java/org/orury/client/gym/application/GymServiceImpl.java
  orury-client/src/main/java/org/orury/client/post/service/PostService.java
  orury-client/src/main/java/org/orury/client/review/application/ReviewFacade.java
  orury-client/src/main/java/org/orury/client/review/interfaces/ReviewController.java
  orury-client/src/main/java/org/orury/client/user/application/UserFacade.java
  orury-client/src/main/java/org/orury/client/user/interfaces/UserController.java
  orury-client/src/main/java/org/orury/client/user/interfaces/response/MyCommentResponse.java
  orury-client/src/test/java/org/orury/client/config/ControllerTest.java
  orury-client/src/test/java/org/orury/client/gym/service/GymServiceTest.java
  orury-client/src/test/java/org/orury/client/user/service/UserServiceTest.java
  orury-domain/src/main/java/org/orury/domain/comment/db/repository/Test.java
  orury-domain/src/main/java/org/orury/domain/comment/domain/CommentReader.java
  orury-domain/src/main/java/org/orury/domain/comment/domain/CommentStore.java
  orury-domain/src/main/java/org/orury/domain/comment/domain/dto/CommentDto.java
  orury-domain/src/main/java/org/orury/domain/comment/domain/dto/CommentLikeDto.java
  orury-domain/src/main/java/org/orury/domain/comment/domain/entity/Comment.java
  orury-domain/src/main/java/org/orury/domain/comment/domain/entity/CommentLike.java
  orury-domain/src/main/java/org/orury/domain/comment/domain/entity/CommentLikePK.java
  orury-domain/src/main/java/org/orury/domain/comment/infrastructure/CommentLikeRepository.java
  orury-domain/src/main/java/org/orury/domain/comment/infrastructure/CommentReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/comment/infrastructure/CommentRepository.java
  orury-domain/src/main/java/org/orury/domain/comment/infrastructure/CommentStoreImpl.java
  orury-domain/src/main/java/org/orury/domain/gym/domain/GymReader.java
  orury-domain/src/main/java/org/orury/domain/gym/infrastructure/GymReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/post/domain/PostServiceImpl.java
  orury-domain/src/main/java/org/orury/domain/post/infrastructure/ImageReaderImpl.java
  orury-domain/src/main/java/org/orury/domain/user/domain/UserServiceImpl.java
  orury-domain/src/test/java/org/orury/domain/config/TestRepositoryUtils.java
Labels: 💻 BE, 🔨 Refactor

#316 Test : Gym(암장) 테스트코드 재작성
  orury-client/build.gradle
  orury-client/src/test/java/org/orury/client/gym/application/GymFacadeTest.java
  orury-client/src/test/java/org/orury/client/gym/application/GymServiceImplTest.java
  orury-client/src/test/java/org/orury/client/gym/controller/GymControllerTest.java
  orury-client/src/test/java/org/orury/client/gym/controller/GymLikeControllerTest.java
  orury-client/src/test/java/org/orury/client/gym/interfaces/GymControllerTest.java
  orury-client/src/test/java/org/orury/client/gym/interfaces/GymLikeControllerTest.java
  orury-client/src/test/java/org/orury/client/gym/service/GymLikeServiceTest.java
  orury-client/src/test/java/org/orury/client/gym/service/GymServiceTest.java
  orury-domain/build.gradle
  orury-domain/src/test/java/org/orury/domain/gym/infrastructure/GymReaderImplTest.java
  orury-domain/src/test/java/org/orury/domain/gym/infrastructure/GymStoreImplTest.java
Labels: 💻 BE, ✅ Test

#322 Fix : api 버저닝에 유연한 Filter의 url 체킹 적용
  orury-client/src/main/java/org/orury/client/auth/jwt/JwtTokenFilter.java
  orury-common/src/main/java/org/orury/common/log/LoggerFilter.java
Labels: 🐞 Fix, 💻 BE
